# Prática 05: Manejo de Heatmaps en  el Análisis de Datos

**Programa de Estudio:** Ingeniería en Entornos Virtuales y Negocios Digitales \
**Asignatura:** Analítica de Datos para Negocios Digitales \
**Docente:** M.T.I. Marco A. Ramírez Hernández \
**Periodo:** Mayo-Agosto 2026 \
**Alumno:** Cristian Isacc Moreno Jimenez


 
# Un Viaje Visual e Informativo - DonorsChoose 

## Ciencia de Datos para el Bien: DonorsChoose 

DonorsChoose es una organización sin fines de lucro con sede en EE.UU. que permite a las personas donar directamente a proyectos de aulas de escuelas públicas. A partir de enero de 2018, 1 millón de proyectos habían sido financiados por DonorsChoose.org. En el 77% de las escuelas públicas de Estados Unidos, al menos un proyecto ha sido solicitado en DonorsChoose.org. DonorsChoose compartió un conjunto de datos completo de todos los proyectos pasados, los recursos relacionados junto con los metadatos de maestros, escuelas, donantes y donaciones. Estos datos pueden usarse para extraer información oculta y crear una solución que permita a DonorsChoose.org construir campañas de correo electrónico dirigidas recomendando solicitudes específicas de aula a donantes anteriores. En este cuaderno, he realizado un análisis en profundidad y exploración del conjunto de datos compartido. Este cuaderno no solo proporciona información del conjunto de datos de donorschoose, sino que también sirve como tutorial para realizar análisis de datos / análisis exploratorio de datos y visualizaciones de datos.

## Contenidos

[1. Preparación de Datos](#1)    

[2. Explorando a los Donantes](#2)       
&thinsp;&thinsp;&thinsp;&thinsp; [2.1 Descripción General de Donantes](#2.1)    
&thinsp;&thinsp;&thinsp;&thinsp; [2.2 Donantes de Diferentes Estados](#2.2)    
&thinsp;&thinsp;&thinsp;&thinsp; [2.3 Estados con Mayor Relación de Donantes a Población](#2.3)      
&thinsp;&thinsp;&thinsp;&thinsp; [2.4 Visualizando Dónde se Ubican los Donantes](#2.5)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; [- 2.4.1 Dónde se Ubican los Donantes en California](#2.4.1)     
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; [- 2.4.2 Dónde se Ubican los Donantes en Florida](#2.4.2)     
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; [- 2.4.3 Dónde se Ubican los Donantes en Nueva York](#2.4.3)     
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; [- 2.4.4 Dónde se Ubican los Donantes en Texas](#2.4.4)     
&thinsp;&thinsp; &thinsp;&thinsp; [2.5 Dónde se Ubican los Donantes](#2.5)      
&thinsp;&thinsp;&thinsp;&thinsp; [2.6 Donantes Maestros y No Maestros en Diferentes Estados](#2.6)    

[3. Explorando las Donaciones](#3)     
&thinsp;&thinsp;&thinsp;&thinsp; [3.1 Descripción General de Donaciones](#3.1)      
&thinsp;&thinsp;&thinsp;&thinsp; [3.2 Proyectos y sus Donaciones](#3.2)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.2.1 Proyectos con Mayor Número de Donantes](#3.2)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.2.2 Proyectos con Mayor Monto Total Financiado](#3.2)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.2.3 Proyectos con Mayor Monto Promedio por Donante](#3.2)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.2.4 Proyectos con Mayor Monto de Donación Individual](#3.2)    
 &thinsp;&thinsp;&thinsp;&thinsp; [3.3 Donantes y sus Donaciones](#3.3)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.3.1 Donantes que Han Realizado el Mayor Número de Donaciones](#3.3)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.3.2 Donantes que Han Financiado los Mayores Montos Totales](#3.3)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.3.3 Donantes que Financian Mayores Montos Promedio en Donaciones Individuales](#3.3)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.3.4 Donantes que Han Financiado el Mayor Monto de Donación Individual](#3.3)    
&thinsp;&thinsp; &thinsp;&thinsp; [3.4 Montos de Donaciones por Año, Mes, Día, Hora](#3.4)     
&thinsp;&thinsp; &thinsp;&thinsp; [3.5 Donaciones Opcionales y Donaciones de Donantes Maestros](#3.5)     
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.5.1 Número y Monto Promedio de Donación: Donaciones Opcionales](#3.5.1)    
&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;&thinsp; &thinsp;&thinsp; [- 3.5.2 Número y Monto Promedio de Donación: Donantes Maestros](#3.5.2)    
 &thinsp;&thinsp; &thinsp;&thinsp; [3.6 Qué Estado ha Recibido el Mayor Monto de Donación](#3.6)     
 &thinsp;&thinsp; &thinsp;&thinsp; [3.7 Qué Estado Recibe los Mayores Montos de Donación Promedio](#3.7)     
 &thinsp;&thinsp; &thinsp;&thinsp; [3.8 Estados y el Total de Donaciones Recibidas](#3.8)     
 &thinsp;&thinsp; &thinsp;&thinsp; [3.9 Donaciones de California a lo Largo del Tiempo](#3.9)     

[4. Explorando a los Maestros](#4)      
&thinsp;&thinsp; &thinsp;&thinsp; [4.1 Descripción General de Datos de Maestros](#4.1)      
&thinsp;&thinsp; &thinsp;&thinsp; [4.2 Quiénes Fueron los Primeros Maestros en DonorsChoose](#4.2)      
&thinsp;&thinsp; &thinsp;&thinsp; [4.3 Crecimiento en el Número de Maestros a lo Largo de los Años](#4.3)      
&thinsp;&thinsp; &thinsp;&thinsp; [4.4 Cuál es la Distribución de Prefijos de Maestros](#4.4)      
&thinsp;&thinsp; &thinsp;&thinsp; [4.5 Serie de Tiempo de Maestros Publicando sus Primeros Proyectos](#4.5)      

[5. Explorando las Escuelas](#5)     
&thinsp;&thinsp; &thinsp;&thinsp; [5.1 Descripción General de Datos de Escuelas](#5.1)      
&thinsp;&thinsp; &thinsp;&thinsp; [5.2 Qué Tipo de Escuelas Publica Proyectos (y Top Estados y Ciudades)](#5.2)      
&thinsp;&thinsp; &thinsp;&thinsp; [5.3 Distribución del Porcentaje de Almuerzo Gratuito en Escuelas](#5.3)      
&thinsp;&thinsp; &thinsp;&thinsp; [5.4 Qué Tipos de Escuelas se Registran en Mayoría](#5.4)      

[6. Explorando los Recursos](#6)     
&thinsp;&thinsp; &thinsp;&thinsp; [6.1 Descripción General de Datos de Recursos](#6.1)      
&thinsp;&thinsp; &thinsp;&thinsp; [6.2 Qué Artículos son Más Populares en Donorschoose](#6.2)      
&thinsp;&thinsp; &thinsp;&thinsp; [6.3 Cuáles son los Artículos Más Caros](#6.3)      
&thinsp;&thinsp; &thinsp;&thinsp; [6.4 Quiénes son los Proveedores Más Populares y Cuál es el Costo Promedio Asociado](#6.4)      

[7. Explorando los Proyectos](#7)     
&thinsp;&thinsp; &thinsp;&thinsp; [7.1 Descripción General de Datos de Proyectos](#7.1)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.2 Categorías, Subcategorías y Categorías de Recursos Más Frecuentes](#7.2)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.3 Tipo de Proyecto y Estado del Proyecto](#7.3)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.4 Día Publicado y Día Financiado](#7.4)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.5 Trimestre Publicado y Trimestre Financiado](#7.5)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.6 En Qué Mes se Publican Más Proyectos](#7.6)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.7 Está Aumentando el Número de Proyectos](#7.7)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.8 En Qué Año y Mes es Mayor el Costo del Proyecto](#7.8)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.9 En Qué Año y Categoría de Grado es Mayor el Costo del Proyecto](#7.9)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.10 Para Qué Categoría de Grado y Categoría de Recurso es Mayor el Costo del Proyecto](#7.10)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.11 Estado del Proyecto por Años](#7.11)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.12 Duración de los Proyectos Financiados Exitosamente](#7.12)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.13 Estado del Proyecto por Diferentes Estados](#7.13)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.14 Costo Promedio de Proyectos por Tipo de Metro de Escuela y Categoría de Recursos](#7.14)      
&thinsp;&thinsp; &thinsp;&thinsp; [7.15 Costo Promedio de Proyectos por Tipo de Metro de Escuela y Categoría de Nivel de Grado](#7.15)      


[8. Análisis de Texto de Proyectos](#8)     
&thinsp;&thinsp; &thinsp;&thinsp; [8.1 Limpieza de Texto](#8.1)      
&thinsp;&thinsp; &thinsp;&thinsp; [8.2 Análisis de Bolsa de Palabras](#8.2)      
&thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; [8.2.1 Palabras/Frases Principales Utilizadas por Maestros en Todos los Ensayos](#8.2.1)      
&thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; [8.2.2 Palabras/Frases Principales Utilizadas en Diferentes Estados](#8.2.2)      
&thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; [8.2.3 Contexto de "Mis Estudiantes Son..."](#8.2.3)      
&thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; [8.2.4 Contexto de "Mis Estudiantes Necesitan..."](#8.2.4)      
&thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; &thinsp;&thinsp; [8.2.5 Título del Proyecto - Palabras Clave Principales Utilizadas](#8.2.5)      


[9. Entendimiento y Comparación de Características de Proyectos](#9)     
&thinsp;&thinsp; &thinsp;&thinsp; [9.1 Proyectos Expirados vs Proyectos Financiados Exitosamente](#9.1)      
&thinsp;&thinsp; &thinsp;&thinsp; [9.2 Proyectos con Duración de Financiamiento Corta vs Larga](#9.2)      
&thinsp;&thinsp; &thinsp;&thinsp; [9.3 Proyectos con Donante Individual vs Múltiples Donantes](#9.3)      

<br>
## <a id="1">1. Preparación de Datos</a> 

Importemos las librerías requeridas y carguemos el conjunto de datos.

In [16]:
%pip install plotly -q
from plotly.offline import init_notebook_mode, iplot
%pip install wordcloud -q
from wordcloud import WordCloud
import plotly.graph_objs as go
import matplotlib.pyplot as plt
# plotly.plotly is deprecated and not needed
from plotly import tools
from datetime import date
%pip install pandas -q
import pandas as pd
import numpy as np 
%pip install seaborn -q
import seaborn as sns
import random 
import warnings
import operator
warnings.filterwarnings("ignore")
init_notebook_mode(connected=True)

path = "../Datasets/"
donors_df = pd.read_csv(path+"Donors.csv")
donations_df = pd.read_csv(path+"Donations.csv")
teachers_df = pd.read_csv(path+"Teachers.csv")

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## <a id="2">2. Explorando a los Donantes</a>

El conjunto de datos de donantes consiste en información sobre cada donante que ha donado al menos una vez en donorschoose, como su ciudad, estado, código postal y estado de maestro.

## <a id="2.1">2.1 Descripción General de Donantes</a>

Veamos una descripción general de las primeras filas del conjunto de datos de donantes

In [17]:
###### total rows
# donors_df.shape

###### total cities 
# len(donors_df['Donor City'].value_counts())

# more than one donation
# t = donations_df['Donor ID'].value_counts().to_frame()
# len(t[t['Donor ID']>1])

donors_df.head(3)

,Donor ID,Donor City,Donor State,Donor Is Teacher,Donor Zip
0,bdd640fb06671ad11c80317fa3b1799d,San Francisco,California,Yes,114
1,8b9d2434e465e150bd9c66b3ad3c2d6d,San Jose,California,Yes,105
2,9a1de644815ef6d13b8faa1837f8a88b,San Francisco,California,No,728

Hay un total de **2,122,640** donantes registrados en DonorsChoose a partir de abril de 2018. Estos donantes pertenecen a **15,204 ciudades diferentes** de Estados Unidos y algunos otros países. De un número tan masivo de donantes, solo **552,941 (es decir, aproximadamente el 26%)** de los donantes han donado más de una vez. Uno de los objetivos principales del desafío Ciencia de Datos para el Bien es encontrar información relevante / recomendaciones para que los donantes puedan ser inspirados nuevamente a donar. Hay aproximadamente 1,471,613 donantes que han realizado solo 1 donación, por lo que DonorsChoose tiene la oportunidad de motivar a estas personas a realizar otro pago.

## <a id="2.2">2.2 Donantes de Cada Estado</a> 
## <a id="2.2.1">2.2.1 Número de Donantes por Estado</a>

In [18]:
%pip install folium -q
import folium
from folium import plugins
from io import StringIO
from folium import plugins
from io import StringIO
from folium import plugins
from io import StringIO
import folium 


statesll=StringIO("""State,Latitude,Longitude
Alabama,32.806671,-86.791130
Alaska,61.370716,-152.404419
Arizona,33.729759,-111.431221
Arkansas,34.969704,-92.373123
California,36.116203,-119.681564
Colorado,39.059811,-105.311104
Connecticut,41.597782,-72.755371
Delaware,39.318523,-75.507141
District of Columbia,38.897438,-77.026817
Florida,27.766279,-81.686783
Georgia,33.040619,-83.643074
Hawaii,21.094318,-157.498337
Idaho,44.240459,-114.478828
Illinois,40.349457,-88.986137
Indiana,39.849426,-86.258278
Iowa,42.011539,-93.210526
Kansas,38.526600,-96.726486
Kentucky,37.668140,-84.670067
Louisiana,31.169546,-91.867805
Maine,44.693947,-69.381927
Maryland,39.063946,-76.802101
Massachusetts,42.230171,-71.530106
Michigan,43.326618,-84.536095
Minnesota,45.694454,-93.900192
Mississippi,32.741646,-89.678696
Missouri,38.456085,-92.288368
Montana,46.921925,-110.454353
Nebraska,41.125370,-98.268082
Nevada,38.313515,-117.055374
New Hampshire,43.452492,-71.563896
New Jersey,40.298904,-74.521011
New Mexico,34.840515,-106.248482
New York,42.165726,-74.948051
North Carolina,35.630066,-79.806419
North Dakota,47.528912,-99.784012
Ohio,40.388783,-82.764915
Oklahoma,35.565342,-96.928917
Oregon,44.572021,-122.070938
Pennsylvania,40.590752,-77.209755
Rhode Island,41.680893,-71.511780
South Carolina,33.856892,-80.945007
South Dakota,44.299782,-99.438828
Tennessee,35.747845,-86.692345
Texas,31.054487,-97.563461
Utah,40.150032,-111.862434
Vermont,44.045876,-72.710686
Virginia,37.769337,-78.169968
Washington,47.400902,-121.490494
West Virginia,38.491226,-80.954453
Wisconsin,44.268543,-89.616508
Wyoming,42.755966,-107.302490""")

tempdf = states_df = donors_df['Donor State'].value_counts()
t1 = pd.DataFrame()
t1['Donor State'] = tempdf.index
t1['Donor Count'] = tempdf.values

# tempdf = combined_df.groupby(['Donor State']).agg({'Donation Amount':'sum'}).reset_index()
# t1 = tempdf.sort_values('Donation Amount', ascending=False)

sdf = pd.read_csv(statesll).rename(columns={'State':'Donor State'})
sdf = sdf.merge(t1, on='Donor State', how='inner')
sdf 

map4 = folium.Map(location=[39.50, -98.35], tiles='CartoDB dark_matter', zoom_start=3.5)
for j, rown in sdf.iterrows():
    rown = list(rown)
    folium.CircleMarker([float(rown[1]), float(rown[2])], popup="<b>State:</b>" + rown[0].title() +"<br> <b>Donors:</b> "+str(int(rown[3])), radius=float(rown[3])*0.0001, color='#be0eef', fill=True).add_to(map4)
map4

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
%pip install nbformat -q

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

> - California, siendo el estado con la mayor población, también tiene una gran base de donantes registrados con aproximadamente 300,000 donantes. **San Francisco y Los Ángeles** son las ciudades principales de California donde se ubican la mayoría de donantes. El número más alto de escuelas y proyectos también es más alto del estado de California.
> - Nueva York, Texas y Florida con aproximadamente 137,000, 134,000 y 108,000 donantes respectivamente son otros tres estados principales con alta población de donantes. Las ciudades principales incluyen Nueva York, Miami, Tampa, Houston y Dallas donde se ubica la mayoría de donantes.
> - Dakota del Norte, Dakota del Sur, Vermont y Wyoming son los estados con un número muy bajo de donantes, menos de 4000. Hay una entrada llamada "otros" en los datos de estados, que probablemente indica donantes maestros o donantes de otros países.
> - Entre todas las ciudades de EE.UU., las tres principales son: **Chicago (aproximadamente 35K donantes), Nueva York (aproximadamente 27K donantes) y Brooklyn (aproximadamente 22K donantes)** con el mayor número de donantes. Las ciudades californiana SF y LA son las siguientes dos ciudades con gran base de donantes con aproximadamente 18K y aproximadamente 16K donantes.

## <a>Conjunto de Datos Ajustado por Población</a>

Los estados principales en los gráficos anteriores son en realidad los estados con población muy alta. Sería interesante averiguar el número de donantes por cada 100,000 personas para cada estado. He añadido un conjunto de datos ajustado por población que incluye la población de cada estado a partir de 2013.

Conjunto de Datos de Población: http://www.enchantedlearning.com/usa/states/population.shtml

## <a id="2.3">2.3 Estados con la Más Alta Relación de **Donantes a Población**</a>

In [20]:
census_2013 = {'Mississippi': 2991207, 'Iowa': 3090416, 'Oklahoma': 3850568, 'Delaware': 925749, 'Minnesota': 5420380, 'Alaska': 735132, 'Illinois': 12882135, 'Arkansas': 2959373, 'New Mexico': 2085287, 'Indiana': 6570902, 'Maryland': 5928814, 'Louisiana': 4625470, 'Texas': 26448193, 'Wyoming': 582658, 'Arizona': 6626624, 'Wisconsin': 5742713, 'Michigan': 9895622, 'Kansas': 2893957, 'Utah': 2900872, 'Virginia': 8260405, 'Oregon': 3930065, 'Connecticut': 3596080, 'New York': 19651127, 'California': 38332521, 'Massachusetts': 6692824, 'West Virginia': 1854304, 'South Carolina': 4774839, 'New Hampshire': 1323459, 'Vermont': 626630, 'Georgia': 9992167, 'North Dakota': 723393, 'Pennsylvania': 12773801, 'Florida': 19552860, 'Hawaii': 1404054, 'Kentucky': 4395295, 'Rhode Island': 1051511, 'Nebraska': 1868516, 'Missouri': 6044171, 'Ohio': 11570808, 'Alabama': 4833722, 'South Dakota': 844877, 'Colorado': 5268367, 'Idaho': 1612136, 'New Jersey': 8899339, 'Washington': 6971406, 'North Carolina': 9848060, 'Tennessee': 6495978, 'Montana': 1015165, 'District of Columbia': 646449, 'Nevada': 2790136, 'Maine': 1328302}

donors_from_states = dict(donors_df['Donor State'].value_counts())

don_pop = {}
for state, don in donors_from_states.items():
    if state not in census_2013:
        continue
    don_pop[state]  = float(don)*100000/ census_2013[state]

import operator
from IPython.display import HTML, display
don_pop = sorted(don_pop.items(), key=operator.itemgetter(1), reverse = True)
xx = [x[0] for x in (don_pop)][1:]
yy = [x[1] for x in (don_pop)][1:]

trace2 = go.Bar(
    x=xx,
    y=yy,
    name='Donors to Population',
    marker=dict(color='green'),
    opacity=0.3
)

data = [trace2]
layout = go.Layout(
    barmode='group',
    legend=dict(dict(x=-.1, y=1.2)),
    margin=dict(b=120),
    title = 'States with highest Donors to Population Ratio',
)

fig = go.Figure(data=data, layout=layout)
%pip install nbformat -q
display(HTML(fig.to_html(include_plotlyjs="cdn", full_html=False)))

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

> - Un gráfico interesante se genera ya que los estados: **Carolina del Sur** (con población = 4774839), **Massachusetts** (con población = 6692824), y **Connecticut** (con población = 3596080) tienen la relación más alta de donantes a población, y el mayor número de donantes por cada 100,000 personas. Carolina del Sur = 985 donantes por 100K personas, Massachusetts = 907 donantes por 100K personas, y Connecticut = 878 donantes por 100K personas.
> - Wyoming, Nebraska y Nuevo México tienen el menor número de donantes por 100K personas igual a 285, 335 y 363 donantes respectivamente.
> - Texas, uno de los estados principales con mayor número de donantes tiene una relación más baja de donantes a población igual a 508 donantes por 100K personas.

## <a id="2.4">2.4 Visualicemos Dónde se Ubican los Donantes</a>
## <a id="2.4.1">2.4.1 Dónde se Ubican los Donantes en California</a>

In [21]:
calcit = StringIO(u"""Name,Latitude,Longitude,Total Donors,Color,Size
Los Angeles,34.052233,-118.243686,"17,922.000000",#0061ff,10
San Francisco,37.774931,-122.419417,"16,553.000000",#0061ff,10
San Diego,32.715328,-117.157256,"9,072.000000",#0061ff,10
San Jose,37.339386,-121.894956,"7,674.000000",#0061ff,10
Oakland,37.804364,-122.271114,"6,783.000000",#0061ff,10
Sacramento,38.581572,-121.494400,"4,701.000000",#0061ff,10
Bakersfield,35.373292,-119.018711,"3,758.000000",#0061ff,10
Long Beach,33.768322,-118.195617,"3,120.000000",#0061ff,10
Berkeley,37.871592,-122.272747,"2,898.000000",#0061ff,10
Irvine,33.683947,-117.794694,"2,765.000000",#0061ff,10
Fremont,37.548269,-121.988572,"2,716.000000",#0061ff,10
Walnut Creek,37.910078,-122.065183,"2,255.000000",#0061ff,10
Huntington Beach,33.660297,-117.999225,"2,185.000000",#0061ff,10
Murrieta,33.553914,-117.213922,"1,982.000000",#0061ff,10
Pleasanton,37.662431,-121.874678,"1,970.000000",#0061ff,10
Torrance,33.83585,-118.340628,"1,957.000000",#0061ff,10
San Mateo,37.562992,-122.325525,"1,956.000000",#0061ff,10
Santa Monica,34.019453,-118.491192,"1,780.000000",#0061ff,10
Livermore,37.681875,-121.768008,"1,776.000000",#0061ff,10
Santa Rosa,38.440467,-122.714431,"1,752.000000",#0061ff,10
Concord,37.977978,-122.031072,"1,623.000000",#0061ff,10
Alameda,37.765206,-122.241636,"1,548.000000",#0061ff,10
Fresno,36.746842,-119.772586,"1,543.000000",#0061ff,10
San Ramon,37.779928,-121.978014,"1,533.000000",#0061ff,10
Anaheim,33.835292,-117.914503,"1,475.000000",#0061ff,10
Pasadena,34.147786,-118.144517,"1,429.000000",#0061ff,10
Glendale,34.142508,-118.255075,"1,427.000000",#0061ff,10
Riverside,33.95335,-117.396156,"1,425.000000",#0061ff,10
Sunnyvale,37.368831,-122.036350,"1,406.000000",#0061ff,10
Chula Vista,32.640053,-117.084197,"1,398.000000",#0061ff,10
Mountain View,37.386053,-122.083850,"1,398.000000",#0061ff,10
Elk Grove,38.4088,-121.371617,"1,397.000000",#0061ff,10
Santa Clarita,34.391664,-118.542586,"1,382.000000",#0061ff,10
Burbank,34.180839,-118.308967,"1,357.000000",#0061ff,10
Redwood City,37.485214,-122.236356,"1,323.000000",#0061ff,10
Chico,39.728494,-121.837478,"1,322.000000",#0061ff,10
Whittier,33.979178,-118.032844,"1,280.000000",#0061ff,10
Corona,33.875294,-117.566439,"1,239.000000",#0061ff,10
Santa Clara,37.354108,-121.955236,"1,233.000000",#0061ff,10
Orange,33.787794,-117.853111,"1,229.000000",#0061ff,10
Palo Alto,37.441883,-122.143019,"1,219.000000",#0061ff,10
Hayward,37.668819,-122.080797,"1,162.000000",#0061ff,10
Oceanside,33.195869,-117.379483,"1,157.000000",#0061ff,10
Fullerton,33.870292,-117.925339,"1,151.000000",#0061ff,10
San Rafael,37.973536,-122.531086,"1,136.000000",#0061ff,10
Folsom,38.677958,-121.176058,"1,125.000000",#0061ff,10
Simi Valley,34.269447,-118.781483,"1,069.000000",#0061ff,10
Escondido,33.119208,-117.086422,"1,062.000000",#0061ff,10
Santa Ana,33.745572,-117.867833,"1,054.000000",#0061ff,10
Redondo Beach,33.849183,-118.388408,"1,048.000000",#34ef6c,8
Stockton,37.957703,-121.290781,"1,041.000000",#34ef6c,8
Santa Cruz,36.974117,-122.030797,"1,029.000000",#34ef6c,8
Culver City,34.021122,-118.396467,"1,019.000000",#34ef6c,8
Salinas,36.677736,-121.655500,"1,017.000000",#34ef6c,8
Martinez,38.019367,-122.134133,975.000000,#34ef6c,8
Santa Barbara,34.420831,-119.698189,936.000000,#34ef6c,8
San Leandro,37.724931,-122.156078,929.000000,#34ef6c,8
Ventura,34.274639,-119.229006,922.000000,#34ef6c,8
Roseville,38.752122,-121.288006,888.000000,#34ef6c,8
Yorba Linda,33.888625,-117.813111,888.000000,#34ef6c,8
Costa Mesa,33.641133,-117.918669,887.000000,#34ef6c,8
San Marcos,33.143372,-117.166144,866.000000,#34ef6c,8
Brentwood,34.057361,-118.480511,853.000000,#34ef6c,8
South San Francisco,37.654656,-122.407750,841.000000,#34ef6c,8
Modesto,37.639097,-120.996878,837.000000,#34ef6c,8
Temecula,33.493639,-117.148364,837.000000,#34ef6c,8
Novato,38.107419,-122.569703,831.000000,#34ef6c,8
Carlsbad,33.158092,-117.350594,822.000000,#34ef6c,8
Mission Viejo,33.600022,-117.671994,817.000000,#34ef6c,8
Brea,33.916681,-117.900061,802.000000,#34ef6c,8
Garden Grove,33.773906,-117.941447,792.000000,#34ef6c,8
Dublin,37.702153,-121.935792,784.000000,#34ef6c,8
El Cajon,32.794772,-116.962528,783.000000,#34ef6c,8
Menlo Park,37.453828,-122.182186,768.000000,#34ef6c,8
Fairfield,38.249358,-122.039967,751.000000,#34ef6c,8
Pleasant Hill,37.947978,-122.060797,725.000000,#34ef6c,8
Napa,38.297539,-122.286864,711.000000,#34ef6c,8
Richmond,37.935758,-122.347750,707.000000,#34ef6c,8
Los Altos,33.796331,-118.118119,703.000000,#34ef6c,8
Daly City,37.687925,-122.470208,702.000000,#34ef6c,8
West Covina,34.068622,-117.938953,688.000000,#34ef6c,8
Lafayette,37.885758,-122.118019,660.000000,#34ef6c,8
La Mesa,32.767828,-117.023083,649.000000,#34ef6c,8
Milpitas,37.428272,-121.906625,649.000000,#34ef6c,8
Carson,33.831406,-118.282017,647.000000,#34ef6c,8
Camarillo,34.216394,-119.037603,643.000000,#34ef6c,8
Petaluma,38.232417,-122.636653,629.000000,#34ef6c,8
Newport Beach,33.618911,-117.928947,626.000000,#34ef6c,8
Pacifica,37.613825,-122.486919,619.000000,#34ef6c,8
Gilroy,37.005783,-121.568275,618.000000,#34ef6c,8
Encinitas,33.036986,-117.291983,607.000000,#34ef6c,8
El Segundo,33.919181,-118.416464,595.000000,#34ef6c,8
Downey,33.940014,-118.132569,592.000000,#34ef6c,8
Rancho Palos Verdes,33.744461,-118.387017,592.000000,#34ef6c,8
San Clemente,33.426972,-117.611992,589.000000,#34ef6c,8
Vacaville,38.356578,-121.987744,584.000000,#34ef6c,8
Chino Hills,33.989819,-117.732586,583.000000,#34ef6c,8
Campbell,37.287164,-121.949958,580.000000,#34ef6c,8
Mill Valley,37.906036,-122.544975,578.000000,#34ef6c,8
El Cerrito,37.916133,-122.310764,576.000000,#f2ae93,6
Emeryville,37.831317,-122.285247,572.000000,#f2ae93,6
Thousand Oaks,34.107231,-118.057847,572.000000,#f2ae93,6
Burlingame,37.584103,-122.366083,570.000000,#f2ae93,6
Antioch,38.004922,-121.805789,568.000000,#f2ae93,6
Beverly Hills,34.073619,-118.400356,568.000000,#f2ae93,6
Lakewood,33.853628,-118.133956,560.000000,#f2ae93,6
Manhattan Beach,33.884736,-118.410908,557.000000,#f2ae93,6
Lancaster,34.686786,-118.154164,551.000000,#f2ae93,6
Oxnard,34.197506,-119.177053,539.000000,#f2ae93,6
San Carlos,37.507158,-122.260522,527.000000,#f2ae93,6
Rocklin,38.790733,-121.235783,526.000000,#f2ae93,6
Placentia,33.872236,-117.870336,520.000000,#f2ae93,6
Cupertino,37.322997,-122.032183,516.000000,#f2ae93,6
Tustin,33.74585,-117.826167,508.000000,#f2ae93,6
Hermosa Beach,33.862236,-118.399519,507.000000,#f2ae93,6
Rancho Cordova,38.589072,-121.302728,501.000000,#f2ae93,6
Fountain Valley,33.709186,-117.953669,498.000000,#f2ae93,6
Cypress,37.320531,-121.962242,497.000000,#f2ae93,6
Union City,37.593392,-122.043831,494.000000,#f2ae93,6
Morgan Hill,37.1305,-121.654389,488.000000,#f2ae93,6
Vallejo,38.104086,-122.256636,485.000000,#f2ae93,6
Alhambra,34.095286,-118.127014,474.000000,#f2ae93,6
Lake Forest,33.646967,-117.689217,465.000000,#f2ae93,6
Rancho Cucamonga,34.1064,-117.593108,463.000000,#f2ae93,6
Vista,33.200036,-117.242536,463.000000,#f2ae93,6
Fontana,34.092233,-117.435047,459.000000,#f2ae93,6
Moreno Valley,33.942467,-117.229672,455.000000,#f2ae93,6
Hawthorne,33.916403,-118.352575,450.000000,#f2ae93,6
Covina,34.090008,-117.890339,443.000000,#f2ae93,6
San Luis Obispo,35.282753,-120.659617,434.000000,#f2ae93,6
Newark,37.529658,-122.040239,433.000000,#f2ae93,6
Inglewood,33.961681,-118.353131,432.000000,#f2ae93,6
Oakley,37.997422,-121.712453,430.000000,#f2ae93,6
Tracy,37.73965,-121.425222,428.000000,#f2ae93,6
Redding,40.586539,-122.391675,424.000000,#f2ae93,6
Glendora,34.136119,-117.865339,423.000000,#f2ae93,6
San Bruno,37.630489,-122.411083,423.000000,#f2ae93,6
Davis,38.544906,-121.740517,417.000000,#f2ae93,6
Westminster,33.751342,-117.993992,413.000000,#f2ae93,6
Pittsburg,38.027975,-121.884681,412.000000,#f2ae93,6
Palmdale,34.579433,-118.116461,408.000000,#f2ae93,6
Visalia,36.330228,-119.292058,406.000000,#f2ae93,6
Poway,32.962822,-117.035864,403.000000,#f2ae93,6
Santa Maria,34.953033,-120.435719,403.000000,#f2ae93,6
Upland,34.097511,-117.648389,396.000000,#f2ae93,6
Laguna Niguel,33.522525,-117.707553,393.000000,#f2ae93,6
La Mirada,33.917236,-118.012008,392.000000,#f2ae93,6
South Pasadena,34.116119,-118.150350,391.000000,#f2ae93,6
Cerritos,33.858347,-118.064786,383.000000,#f2ae93,6
Lodi,38.134147,-121.272219,380.000000,#f2ae93,6
Ontario,34.063344,-117.650889,380.000000,#bab7b6,4
Lincoln,38.891564,-121.293008,376.000000,#bab7b6,4
Buena Park,33.867514,-117.998117,375.000000,#bab7b6,4
Rancho Santa Margarita,33.640856,-117.603103,373.000000,#bab7b6,4
Santee,32.838383,-116.973917,373.000000,#bab7b6,4
Sonoma,38.291858,-122.458036,372.000000,#bab7b6,4
Monrovia,34.144428,-118.001947,371.000000,#bab7b6,4
Albany,37.886869,-122.297747,368.000000,#bab7b6,4
La Habra,33.931958,-117.946172,366.000000,#bab7b6,4
San Pablo,37.962147,-122.345525,366.000000,#bab7b6,4
Belmont,37.520214,-122.275800,364.000000,#bab7b6,4
Pomona,34.055228,-117.752306,364.000000,#bab7b6,4
Gardena,33.88835,-118.308961,363.000000,#bab7b6,4
Arcadia,34.139728,-118.035344,361.000000,#bab7b6,4
Clovis,36.825228,-119.702919,360.000000,#bab7b6,4
Orinda,37.877147,-122.179689,358.000000,#bab7b6,4
Manteca,37.797428,-121.216053,357.000000,#bab7b6,4
Citrus Heights,38.707125,-121.281061,355.000000,#bab7b6,4
Redlands,34.055569,-117.182539,353.000000,#bab7b6,4
Aliso Viejo,33.575,-117.725556,345.000000,#bab7b6,4
Eureka,40.802072,-124.163672,338.000000,#bab7b6,4
West Hollywood,34.090008,-118.361744,337.000000,#bab7b6,4
Auburn,38.896564,-121.076889,335.000000,#bab7b6,4
Saratoga,37.263833,-122.023014,331.000000,#bab7b6,4
Turlock,37.494658,-120.846594,327.000000,#bab7b6,4
Chino,34.012236,-117.688944,325.000000,#bab7b6,4
Diamond Bar,34.028622,-117.810336,324.000000,#bab7b6,4
South Gate,33.954736,-118.212017,319.000000,#bab7b6,4
San Bernardino,34.108344,-117.289764,318.000000,#bab7b6,4
Claremont,34.096675,-117.719778,316.000000,#bab7b6,4
Calabasas,34.138333,-118.660833,298.000000,#bab7b6,4
Los Alamitos,33.803072,-118.072564,297.000000,#bab7b6,4
Agoura Hills,34.153339,-118.761675,295.000000,#bab7b6,4
San Gabriel,34.096111,-118.105833,295.000000,#bab7b6,4
Paso Robles,35.632278,-120.664186,292.000000,#bab7b6,4
Norwalk,33.902236,-118.081733,286.000000,#bab7b6,4
Indio,33.720578,-116.215561,284.000000,#bab7b6,4
Moorpark,34.144897,-118.268742,284.000000,#bab7b6,4
Monterey,36.600239,-121.894675,275.000000,#bab7b6,4
Arroyo Grande,35.118586,-120.590725,274.000000,#bab7b6,4
San Dimas,34.106675,-117.806725,274.000000,#bab7b6,4
La Puente,34.020011,-117.949508,273.000000,#bab7b6,4
West Sacramento,38.580461,-121.530233,273.000000,#bab7b6,4
Rohnert Park,38.339636,-122.701097,269.000000,#bab7b6,4
Monterey Park,34.062511,-118.122847,266.000000,#bab7b6,4
Laguna Hills,33.599722,-117.699444,260.000000,#bab7b6,4
Watsonville,36.910231,-121.756894,259.000000,#bab7b6,4
Clayton,37.941033,-121.935792,256.000000,#bab7b6,4
Hemet,33.747519,-116.971967,256.000000,#bab7b6,4
La Verne,34.100842,-117.767836,255.000000,#bab7b6,4
Ukiah,39.150172,-123.207783,255.000000,#f477d7,2
Palm Desert,33.722244,-116.374456,251.000000,#f477d7,2
Atascadero,35.489417,-120.670725,241.000000,#f477d7,2
Menifee,33.678333,-117.166944,241.000000,#f477d7,2
Lompoc,34.63915,-120.457942,240.000000,#f477d7,2
Merced,37.302164,-120.482967,240.000000,#f477d7,2
Sebastopol,38.402136,-122.823881,237.000000,#f477d7,2
Lake Elsinore,33.668078,-117.327261,236.000000,#f477d7,2
Millbrae,37.598547,-122.387194,234.000000,#f477d7,2
Yuba City,39.140447,-121.616911,231.000000,#f477d7,2
Woodland,38.678517,-121.773297,228.000000,#f477d7,2
Bellflower,33.881683,-118.117011,227.000000,#f477d7,2
Grass Valley,39.219061,-121.061061,227.000000,#f477d7,2
Seal Beach,33.741406,-118.104786,227.000000,#f477d7,2
Walnut,34.020289,-117.865339,227.000000,#f477d7,2
Montebello,34.016506,-118.113753,225.000000,#f477d7,2
Yucaipa,34.033625,-117.043086,225.000000,#f477d7,2
Hanford,36.32745,-119.645683,224.000000,#f477d7,2
Goleta,34.435828,-119.827639,221.000000,#f477d7,2
Hesperia,34.426389,-117.300878,221.000000,#f477d7,2
Laguna Beach,33.542247,-117.783111,221.000000,#f477d7,2
Ridgecrest,35.622456,-117.670897,218.000000,#f477d7,2
Galt,38.254636,-121.299947,217.000000,#f477d7,2
Victorville,34.536108,-117.291158,217.000000,#f477d7,2
San Juan Capistrano,33.501692,-117.662550,209.000000,#f477d7,2
Atwater,37.347717,-120.609083,208.000000,#f477d7,2
Palm Springs,33.830297,-116.545292,208.000000,#f477d7,2
Azusa,34.133619,-117.907564,203.000000,#f477d7,2
Hercules,38.017144,-122.288581,202.000000,#f477d7,2
Sonora,37.984092,-120.382139,199.000000,#f477d7,2
Beaumont,33.929461,-116.977247,198.000000,#f477d7,2
Half Moon Bay,37.463553,-122.428586,197.000000,#f477d7,2
Hollister,36.852453,-121.401603,196.000000,#f477d7,2
Westlake Village,34.145839,-118.805647,194.000000,#f477d7,2
Pico Rivera,33.983069,-118.096736,190.000000,#f477d7,2
Pinole,38.004367,-122.298858,186.000000,#f477d7,2
Compton,33.89585,-118.220072,185.000000,#f477d7,2
Sausalito,37.859094,-122.485250,183.000000,#f477d7,2
La Quinta,33.646692,-116.310008,181.000000,#f477d7,2
Dana Point,33.466972,-117.698108,175.000000,#f477d7,2
Rialto,34.1064,-117.370325,172.000000,#f477d7,2
Perris,33.782519,-117.228647,171.000000,#f477d7,2
Arcata,40.866517,-124.082839,168.000000,#f477d7,2
Pacific Grove,36.617736,-121.916622,168.000000,#f477d7,2
Lomita,33.792239,-118.315072,167.000000,#f477d7,2
San Fernando,34.281947,-118.438972,165.000000,#f477d7,2
South Lake Tahoe,38.939925,-119.977186,163.000000,#f477d7,2
El Monte,34.068622,-118.027567,158.000000,#f477d7,2
Scotts Valley,37.051061,-122.014683,158.000000,#f477d7,2
Tehachapi,35.132189,-118.448975,157.000000,#f477d7,2
Baldwin Park,34.085286,-117.960897,156.000000,#f477d7,2
Marina,36.684403,-121.802172,155.000000,#f477d7,2
Rosemead,34.080564,-118.072847,155.000000,#f477d7,2
Placerville,38.729625,-120.798547,151.000000,#f477d7,2
Highland,34.128344,-117.208650,148.000000,#f477d7,2
Lawndale,33.887236,-118.352575,143.000000,#f477d7,2
Oroville,39.513775,-121.556358,142.000000,#f477d7,2
Seaside,33.819361,-118.366647,142.000000,#f477d7,2
Wildomar,33.598914,-117.280036,142.000000,#f477d7,2
Duarte,34.13945,-117.977286,141.000000,#f477d7,2
Huntington Park,33.981681,-118.225072,141.000000,#f477d7,2
Larkspur,37.934092,-122.535253,139.000000,#f477d7,2
Del Mar,32.959489,-117.265314,138.000000,#f477d7,2
Winters,38.524906,-121.970803,138.000000,#f477d7,2
Red Bluff,40.178489,-122.235831,137.000000,#f477d7,2
Cathedral City,33.779742,-116.465292,136.000000,#f9e84a,1
Ojai,34.44805,-119.242889,136.000000,#f9e84a,1
Coronado,32.685886,-117.183089,134.000000,#f9e84a,1
Lynwood,33.930292,-118.211461,134.000000,#f9e84a,1
Temple City,34.107231,-118.057847,132.000000,#f9e84a,1
Bell,33.977514,-118.187017,124.000000,#f9e84a,1
Sierra Madre,34.161672,-118.052847,119.000000,#f9e84a,1
Nevada City,39.261561,-121.016058,118.000000,#f9e84a,1
National City,32.678108,-117.099197,117.000000,#f9e84a,1
Ceres,37.594933,-120.957711,116.000000,#f9e84a,1
Solana Beach,32.991156,-117.271147,115.000000,#f9e84a,1
La Palma,33.846403,-118.046731,114.000000,#f9e84a,1
Healdsburg,38.610467,-122.869161,110.000000,#f9e84a,1
Ripon,37.739453,-121.135414,109.000000,#f9e84a,1
Crescent City,41.755947,-124.201747,108.000000,#f9e84a,1
Malibu,34.005008,-118.810172,108.000000,#f9e84a,1
Patterson,37.4716,-121.129656,107.000000,#f9e84a,1
Maywood,33.986681,-118.185350,105.000000,#f9e84a,1
Suisun City,38.238247,-122.040244,105.000000,#f9e84a,1
Dixon,38.445464,-121.823297,104.000000,#f9e84a,1
Fort Bragg,39.445722,-123.805292,103.000000,#f9e84a,1
Oakdale,37.766594,-120.847153,103.000000,#f9e84a,1
American Canyon,38.174917,-122.260803,100.000000,#f9e84a,1
Lemon Grove,32.742553,-117.031417,97.000000,#f9e84a,1
Carpinteria,34.398883,-119.518456,96.000000,#f9e84a,1
Lemoore,36.300783,-119.782911,96.000000,#f9e84a,1
San Jacinto,33.783908,-116.958636,95.000000,#f9e84a,1
San Marino,34.121397,-118.106458,95.000000,#f9e84a,1
Paramount,33.889461,-118.159792,94.000000,#f9e84a,1
Tulare,36.207728,-119.347339,93.000000,#f9e84a,1
Twentynine Palms,34.135558,-116.054169,92.000000,#f9e84a,1
Shafter,35.500514,-119.271775,91.000000,#f9e84a,1
Norco,33.931125,-117.548661,89.000000,#f9e84a,1
Capitola,36.975228,-121.953292,88.000000,#f9e84a,1
Rio Vista,38.15575,-121.691344,88.000000,#f9e84a,1
Colton,34.073903,-117.313656,86.000000,#f9e84a,1
Brisbane,37.680767,-122.399972,85.000000,#f9e84a,1
Taft,35.142467,-119.456508,85.000000,#f9e84a,1
Imperial Beach,32.583944,-117.113086,84.000000,#f9e84a,1
Kingsburg,36.513839,-119.554017,84.000000,#f9e84a,1
Morro Bay,35.365808,-120.849900,83.000000,#f9e84a,1
Santa Fe Springs,33.947236,-118.085344,83.000000,#f9e84a,1
Rancho Mirage,33.739744,-116.412789,78.000000,#f9e84a,1
Stanton,33.802517,-117.993117,78.000000,#f9e84a,1
Madera,36.961336,-120.060717,77.000000,#f9e84a,1
Los Banos,37.058278,-120.849914,76.000000,#f9e84a,1
Riverbank,37.736039,-120.935489,76.000000,#f9e84a,1
Gridley,39.363778,-121.693583,75.000000,#f9e84a,1
Pismo Beach,35.142753,-120.641283,74.000000,#f9e84a,1
Santa Paula,34.354167,-119.059269,74.000000,#f9e84a,1
Cotati,38.327778,-122.709167,73.000000,#f9e84a,1
Port Hueneme,34.180728,-119.208158,73.000000,#f9e84a,1
Selma,36.570783,-119.612075,73.000000,#f9e84a,1
Banning,33.925572,-116.876411,71.000000,#f9e84a,1
King City,36.212744,-121.126028,71.000000,#f9e84a,1
El Centro,32.792,-115.563050,69.000000,#f9e84a,1
Lakeport,39.04295,-122.915828,69.000000,#f9e84a,1
Willits,39.409608,-123.355567,68.000000,#f9e84a,1
Barstow,34.895797,-117.017283,67.000000,#f9e84a,1
Marysville,39.145725,-121.591356,67.000000,#f9e84a,1
Orland,39.747381,-122.196375,66.000000,#f9e84a,1
Grand Terrace,34.033903,-117.313653,63.000000,#f9e84a,1
Montclair,34.077511,-117.689778,63.000000,#f9e84a,1
Villa Park,33.814461,-117.813111,63.000000,#f9e84a,1
Artesia,33.865847,-118.083122,62.000000,#f9e84a,1
Desert Hot Springs,33.961125,-116.501678,61.000000,#f9e84a,1
Fortuna,40.598186,-124.157275,61.000000,#f9e84a,1
Grover Beach,35.121642,-120.621283,61.000000,#f9e84a,1
Loma Linda,34.048347,-117.261153,59.000000,#f9e84a,1
Dinuba,36.543283,-119.387067,58.000000,#f9e84a,1
South El Monte,34.051956,-118.046733,58.000000,#f9e84a,1
Porterville,36.065231,-119.016767,57.000000,#f9e84a,1
Lathrop,37.822706,-121.276611,56.000000,#f9e84a,1
Coalinga,36.139678,-120.360150,55.000000,#f9e84a,1
Fillmore,34.399164,-118.918153,54.000000,#f9e84a,1
Mount Shasta,41.410806,-122.194575,52.000000,#f9e84a,1
Anderson,40.448208,-122.297783,51.000000,#f9e84a,1
Cloverdale,38.805461,-123.017222,50.000000,#f9e84a,1
Exeter,36.296061,-119.142053,50.000000,#f9e84a,1
Wasco,35.594125,-119.340947,50.000000,#f9e84a,1
Reedley,36.596339,-119.450403,47.000000,#f9e84a,1
Sanger,36.708006,-119.555964,47.000000,#f9e84a,1
Adelanto,34.582769,-117.409214,45.000000,#f9e84a,1
Brawley,32.978658,-115.530267,43.000000,#f9e84a,1
Calimesa,34.003903,-117.061975,42.000000,#f9e84a,1
Hughson,37.602725,-120.866481,42.000000,#f9e84a,1
Imperial,32.847553,-115.569439,41.000000,#f9e84a,1
Soledad,32.991156,-117.271147,41.000000,#f9e84a,1
Weed,41.42265,-122.386128,40.000000,#f9e84a,1
Calexico,32.678947,-115.498883,37.000000,#f9e84a,1
Willows,39.524325,-122.193592,36.000000,#f9e84a,1
Big Bear Lake,34.243897,-116.911422,35.000000,#f9e84a,1
Delano,35.768842,-119.247053,34.000000,#f9e84a,1
Newman,37.313828,-121.020761,34.000000,#f9e84a,1
Colfax,39.100731,-120.953275,33.000000,#f9e84a,1
Escalon,37.797428,-120.996603,33.000000,#f9e84a,1
Jackson,38.348803,-120.774103,32.000000,#f9e84a,1
Bishop,37.363539,-118.395111,31.000000,#f9e84a,1
Coachella,33.6803,-116.173894,31.000000,#f9e84a,1
Holtville,32.811161,-115.380264,31.000000,#f9e84a,1
Indian Wells,33.717631,-116.340756,31.000000,#f9e84a,1
San Juan Bautista,36.845511,-121.537997,31.000000,#f9e84a,1
Arvin,35.2018,-118.833106,30.000000,#f9e84a,1
Kerman,36.723558,-120.059878,30.000000,#f9e84a,1
Colusa,39.214333,-122.009417,27.000000,#f9e84a,1
Greenfield,36.3208,-121.243814,27.000000,#f9e84a,1
Waterford,37.641319,-120.760483,26.000000,#f9e84a,1
Ferndale,40.576242,-124.263944,25.000000,#f9e84a,1
Susanville,40.416283,-120.653006,25.000000,#f9e84a,1
Buellton,34.613597,-120.192650,24.000000,#f9e84a,1
Calistoga,38.578797,-122.579706,24.000000,#f9e84a,1
Clearlake,38.958231,-122.626372,24.000000,#f9e84a,1
Shasta Lake,40.680428,-122.370842,24.000000,#f9e84a,1
Yreka,41.735419,-122.634472,23.000000,#f9e84a,1
Biggs,39.412389,-121.712750,22.000000,#f9e84a,1
Chowchilla,37.123,-120.260175,22.000000,#f9e84a,1
Live Oak,36.983561,-121.980517,22.000000,#f9e84a,1
McFarland,35.678011,-119.229275,22.000000,#f9e84a,1
Fowler,36.630506,-119.678469,21.000000,#f9e84a,1
Gonzales,36.506628,-121.444381,21.000000,#f9e84a,1
Solvang,34.595819,-120.137647,21.000000,#f9e84a,1
Angels Camp,38.067783,-120.538531,20.000000,#f9e84a,1
Gustine,37.257717,-120.998814,20.000000,#f9e84a,1
Sutter Creek,38.392967,-120.802436,20.000000,#f9e84a,1
Wheatland,39.009894,-121.423014,20.000000,#f9e84a,1
Hawaiian Gardens,33.831403,-118.072842,19.000000,#f9e84a,1
Lindsay,36.203006,-119.088161,19.000000,#f9e84a,1
Livingston,37.386883,-120.723533,19.000000,#f9e84a,1
California City,35.1258,-117.985903,18.000000,#f9e84a,1
Corning,39.927658,-122.179156,18.000000,#f9e84a,1
Trinidad,41.059292,-124.143125,18.000000,#f9e84a,1
Ione,38.352692,-120.932717,17.000000,#f9e84a,1
Dunsmuir,41.208208,-122.271953,16.000000,#f9e84a,1
Tulelake,41.955989,-121.477492,15.000000,#f9e84a,1
Firebaugh,36.858839,-120.456008,13.000000,#f9e84a,1
Woodlake,36.413561,-119.098717,13.000000,#f9e84a,1
Blue Lake,40.882908,-123.983950,12.000000,#f9e84a,1
Blythe,33.617233,-114.589175,12.000000,#f9e84a,1
Avalon,33.342819,-118.328228,11.000000,#f9e84a,1
Montague,41.728197,-122.527800,11.000000,#f9e84a,1
Williams,39.154614,-122.149419,11.000000,#f9e84a,1
Alturas,41.487114,-120.542456,10.000000,#f9e84a,1
Corcoran,37.977978,-122.031072,9.000000,#f9e84a,1
Isleton,38.161861,-121.611622,9.000000,#f9e84a,1
Piedmont,37.824372,-122.231636,9.000000,#f9e84a,1
Rio Dell,40.4993,-124.106436,9.000000,#f9e84a,1
Huron,36.202731,-120.102917,8.000000,#f9e84a,1
Point Arena,38.908797,-123.693072,8.000000,#f9e84a,1
Dorris,41.967369,-121.918061,7.000000,#f9e84a,1
Dos Palos,36.986058,-120.626572,7.000000,#f9e84a,1
Etna,41.456806,-122.894756,6.000000,#f9e84a,1
Guadalupe,34.971644,-120.571836,6.000000,#f9e84a,1
Needles,34.848061,-114.614133,6.000000,#f9e84a,1
Plymouth,38.481853,-120.844658,5.000000,#f9e84a,1
Avenal,36.004122,-120.129028,4.000000,#f9e84a,1
Fort Jones,41.663864,-124.252892,4.000000,#f9e84a,1
Portola,39.810458,-120.469103,4.000000,#f9e84a,1
Calipatria,33.125597,-115.514153,3.000000,#f9e84a,1
Farmersville,36.297728,-119.206778,3.000000,#f9e84a,1
Loyalton,39.676294,-120.241039,3.000000,#f9e84a,1
Maricopa,35.058858,-119.400950,2.000000,#f9e84a,1
Parlier,36.611617,-119.527072,2.000000,#f9e84a,1
Bell Gardens,33.965292,-118.151458,1.000000,#f9e84a,1
Orange Cove,36.624394,-119.313731,1.000000,#f9e84a,1
San Joaquin,36.606617,-120.189044,1.000000,#f9e84a,1
Westmorland,33.037267,-115.621383,1.000000,#f9e84a,1""")



cities = pd.read_csv(calcit)
cities = cities.dropna()

# map_osm = folium.Map(location=[36.611617,-119.527072], zoom_start=5)

# for i, row in cities.iterrows():
#     folium.CircleMarker([row['Latitude'], row['Longitude']],
#                         radius=row['Size'],
#                         color=row['Color'],
#                         fill_color=row['Color'],
#                        ).add_to(map_osm)



map_osm2 = folium.Map([36.611617,-119.527072], zoom_start=6,tiles='cartodbdark_matter')
ziparr = []
for i, row in cities.iterrows():
    ziparr.append([row['Latitude'],row['Longitude'], float(row['Total Donors'].replace(",",""))])
map_osm2.add_child(plugins.HeatMap(ziparr, radius=12))
map_osm2

> Las ubicaciones clave donde la densidad de donantes es más alta son las siguientes:

    - Los Ángeles, 17,922
    - San Francisco, 16,553
    - San Diego, 9,072
    - San José, 7,674
    - Oakland, 6,783

## <a id="2.4.2">2.4.2 Dónde se Ubican los Donantes en Florida</a>

In [22]:
try:
    c = pd.read_csv("../input/cities/zip_codes_states.csv")
except FileNotFoundError:
    c = pd.DataFrame({
        "city": ["Miami", "Tampa", "Orlando", "Jacksonville", "Fort Lauderdale", "West Palm Beach"],
        "state": ["FL"] * 6,
        "latitude": [25.7617, 27.9506, 28.5383, 30.3322, 26.1224, 26.7153],
        "longitude": [-80.1918, -82.4572, -81.3792, -81.6557, -80.1373, -80.0534],
    })
c = c.dropna()

fldf = c[c['state'] == 'FL'][['city', 'latitude', 'longitude']]

fldf = fldf.groupby('city').agg({'latitude': 'max', 'longitude': 'max'}).reset_index()
t = donors_df[donors_df['Donor State'] == 'Florida']['Donor City'].value_counts()
fldons = pd.DataFrame()
fldons['city'] = t.index
fldons['count'] = t.values
florida = fldons.merge(fldf, on='city', how='left').dropna()


map_osm2 = folium.Map([29.813456, -82.472049], zoom_start=6.2,tiles='cartodbdark_matter')
ziparr = []
for i, row in florida.iterrows():
    ziparr.append([row['latitude'],row['longitude'], row['count']])
map_osm2.add_child(plugins.HeatMap(ziparr, radius=12))

> La región tri-condado de Florida: Palm Beach, Miami-Dade, Broward tiene la alta concentración de donantes. La ciudad capital: Tampa también tiene un número significativo de donantes. Algunos donantes también se encuentran en una de las áreas más caras y el extremo más sureño de EE.UU. llamado área de Key West en Florida. Los siguientes son los conteos respectivos y números de donantes de las 5 ciudades principales:

> Miami (9309), Tampa (6016), Orlando (5658), Jacksonville (4598), Fort Lauderdale (4311), West Palm Beach (2400)

## <a id="2.4.3">2.4.3 Dónde se Ubican los Donantes en Nueva York</a>

In [23]:
fldf = c[c['state'] == 'NY'][['city', 'latitude', 'longitude']]
fldf = fldf.groupby('city').agg({'latitude': 'max', 'longitude': 'max'}).reset_index()
fldf
t = donors_df[donors_df['Donor State'] == 'New York']['Donor City'].value_counts()

fldons = pd.DataFrame()
fldons['city'] = t.index
fldons['count'] = t.values
florida = fldons.merge(fldf, on='city', how='left').dropna()


map_osm2 = folium.Map([42.315975, -74.065515], zoom_start=6.2,tiles='cartodbdark_matter')
ziparr = []
for i, row in florida.iterrows():
    ziparr.append([row['latitude'],row['longitude'], row['count']])
map_osm2.add_child(plugins.HeatMap(ziparr, radius=12))

> Los donantes de Nueva York son principalmente de la Ciudad de Nueva York. Las 5 ciudades principales son:
- Nueva York                26820
- Brooklyn                  21715
- Staten Island              4516
- El Bronx                   4455
- Buffalo                    2232

## <a id="2.4.4">2.4.4 Dónde se Ubican los Donantes en Texas</a>

In [24]:
fldf = c[c['state'] == 'TX'][['city', 'latitude', 'longitude']]
fldf = fldf.groupby('city').agg({'latitude': 'max', 'longitude': 'max'}).reset_index()
fldf
t = donors_df[donors_df['Donor State'] == 'Texas']['Donor City'].value_counts()

fldons = pd.DataFrame()
fldons['city'] = t.index
fldons['count'] = t.values
florida = fldons.merge(fldf, on='city', how='left').dropna()


map_osm2 = folium.Map([31.884540, -97.077218], zoom_start=6.2,tiles='cartodbdark_matter')
ziparr = []
for i, row in florida.iterrows():
    ziparr.append([row['latitude'],row['longitude'], row['count']])
map_osm2.add_child(plugins.HeatMap(ziparr, radius=12))

> Las ciudades principales de Texas donde se ubican los donantes son:

- Houston             15404
- Austin               9958
- Dallas               7818
- San Antonio          6465
- Fort Worth           4350

## <a id="2.5">2.5 ¿Dónde se Ubican los Donantes?</a>

In [25]:
fldf = c[['city', 'latitude', 'longitude']]
fldf = fldf.groupby('city').agg({'latitude': 'max', 'longitude': 'max'}).reset_index()
fldf
t = donors_df['Donor City'].value_counts()
fldons = pd.DataFrame()
fldons['city'] = t.index
fldons['count'] = t.values
florida = fldons.merge(fldf, on='city', how='left').dropna()


map_osm2 = folium.Map([39.3714557,-94.3541242], zoom_start=3.5,tiles='cartodbdark_matter')
ziparr = []
for i, row in florida.iterrows():
    ziparr.append([row['latitude'],row['longitude'], row['count']])
map_osm2.add_child(plugins.HeatMap(ziparr, radius=10))

>  Aunque el número máximo de donantes son del Estado de California que se ubica en la costa oeste, la región de la costa este de EE.UU. tiene mayor densidad de donantes en comparación con el oeste. Un número significativo de donantes se ubican también en Hawaii y Alaska.

## <a id="2.6">2.6 Número de Donantes Maestros y No Maestros de Cada Estado</a>

In [26]:
# which city and state has maximum teacher donors 
tempdf = donors_df.groupby(['Donor State', 'Donor Is Teacher']).agg({'Donor Is Teacher' : 'count' }).rename(columns={'Donor Is Teacher' : 'Teacher Donor Counts'}).reset_index()

no_df = tempdf[tempdf['Donor Is Teacher']=='No']
no_x = no_df['Donor State']
no_y = no_df['Teacher Donor Counts']
yes_df = tempdf[tempdf['Donor Is Teacher']=='Yes']
yes_x = yes_df['Donor State']
yes_y = yes_df['Teacher Donor Counts']

trace1 = go.Bar(
    x=no_x,
    y=no_y,
    name='Non Teacher Donors',
    marker=dict(color='#f259d6'),
    opacity=0.8
)
trace2 = go.Bar(
    x=yes_x,
    y=yes_y,
    name='Teacher Donors',
    marker=dict(color='#f7bb31'),
    opacity=0.8
)

data = [trace1, trace2]
layout = go.Layout(
    barmode='group',
    legend=dict(dict(x=-.1, y=1.2)),
    margin=dict(b=120),
    title = 'States and the distribution of Teacher and Non Teacher Donors',
)

fig = go.Figure(data=data, layout=layout)
display(HTML(fig.to_html(include_plotlyjs="cdn", full_html=False)))

> El número de donantes maestros es siempre muy bajo en todos los estados. Los registros que tienen estado igual a "otros" tienen el mayor número de donantes maestros igual a aproximadamente 28,000.

## <a id="3">3. Exploración de Donaciones</a>

El archivo de donaciones incluye información sobre donaciones realizadas por los donantes, monto total de donación, secuencia del carrito del donante, fecha, proyecto e ID del donante.

## <a id="3.1">3.1 Descripción General de Donaciones</a>

In [27]:
donations_df[['Donation ID', 'Donation Included Optional Donation', 'Donation Amount',
       'Donor Cart Sequence', 'Donation Received Date', 'Project ID', 'Donor ID']].head(3)
# donations_df.columns

# len(donations_df)
# len(donations_df[donations_df['Donation Amount'] > 20000]) / len(donations_df)
# len(donations_df[donations_df['Donation Amount'] > 10000]) / len(donations_df)
# len(donations_df[donations_df['Donation Amount'] < 1])
# np.mean(donations_df['Donation Amount'])

,Donation ID,Donation Included Optional Donation,Donation Amount,Donor Cart Sequence,Donation Received Date,Project ID,Donor ID
0,0f1259e0a18ff6b6b535106e122c9a56,No,2219.27,2,2016-06-10 07:17:42,a013ac6ededa4e161b3dbd5ce9a1fa6f,17fc695a07a0ca6e0822e8f36c031199
1,21df306f8a0b3c3336d8393a7c441fe7,Yes,44.02,8,2017-04-06 13:12:06,b09b2a5cbadcc32ac1590f538a0f4efb,366eb16f508ebad7b7c93acfe059a0ee
2,5ab33edf6e595ed3a8b317fa18d0752b,Yes,112.07,11,2016-10-31 20:06:03,5cec4eb5edd968311ca35cfb04fc6d82,aefcfad8efc89849b3aa7efe4458a885

Ha habido un total de **4,687,884 donaciones** a partir de abril de 2018 en donorschoose. El monto más alto donado es igual a **USD 60,000** donados en 2013. Solo **6 donaciones son mayores que USD 20,000** mientras que solo **61 pagos son mayores que USD 10,000**. La mayoría de los pagos (aproximadamente **83%** de todas las donaciones) son **menos de USD 100**. Hay 350 pagos que son menos de USD 1 -> cantidad pequeña, pero aún puede hacer diferencia. A partir de abril de 2018, DonorsChoose ha recaudado una cantidad colosal igual a **USD 284,408,243** a través de su plataforma. El monto promedio donado en donorschoose es igual a USD 60. Veamos los detalles de donantes y proyectos relacionados con estas donaciones en las siguientes secciones.

## <a id="3.2">3.2 Proyectos y sus Donaciones</a>

Identifiquemos los mejores proyectos y sus valores de atributos relacionados:

- 3.2.1 Proyectos con Mayor Número de Donantes
- 3.2.2 Proyectos con Mayor Monto Total Financiado
- 3.2.3 Proyectos con Mayor Monto Promedio por Donante
- 3.2.4 Proyectos con Mayor Monto de Donación Individual

In [28]:
# Which Projects Had the maximum Donations 

tempdf = donations_df.groupby('Project ID').agg({'Project ID': 'count', 'Donation Amount': 'sum'}).rename(
    columns={'Project ID': "Total Donations", 'Donation Amount': "Total Amount"}
).reset_index()
tempdf['Average Donation Amount'] = tempdf['Total Amount'] / tempdf['Total Donations']

tempdf1 = tempdf.sort_values(by=['Total Donations'], ascending=[False])
x = tempdf1.head(5)['Project ID']
x = ["Pa" + str(i + 1) for i in range(len(x))]
y = tempdf1.head(5)['Total Donations']
tr1 = bar_ver_noagg(x, y, 'Total Donations', '#43ef4b', lm=None, rt=True)

tempdf1 = tempdf.sort_values(by=['Total Amount'], ascending=[False])
x = tempdf1.head(5)['Project ID']
x = ["Pb" + str(i + 1) for i in range(len(x))]
y = tempdf1.head(5)['Total Amount']
tr2 = bar_ver_noagg(x, y, 'Average Donations', '#7fef84', lm=None, rt=True)

tempdf1 = tempdf.sort_values(by=['Average Donation Amount'], ascending=[False])
x = tempdf1[tempdf1['Total Donations'] > 10].head(5)['Project ID']
x = ["Pc" + str(i + 1) for i in range(len(x))]
y = tempdf1[tempdf1['Total Donations'] > 10].head(5)['Average Donation Amount']
tr3 = bar_ver_noagg(x, y, 'Average Donations (Min: 10 Donations)', '#a5d1a7', lm=None, rt=True)

tempdf = donations_df.groupby('Project ID').agg({'Project ID': 'count', 'Donation Amount': 'max'}).rename(
    columns={'Project ID': "Total Donations", 'Donation Amount': "Maximum Donations"}
).reset_index()
tempdf1 = tempdf.sort_values(by=['Maximum Donations'], ascending=[False])
x = tempdf1.head(5)['Project ID']
x = ["Pd" + str(i + 1) for i in range(len(x))]
y = tempdf1.head(5)['Maximum Donations']
tr4 = bar_ver_noagg(x, y, 'Maximum Donations', '#c0d1c1', lm=None, rt=True)

fig = tools.make_subplots(
    rows=2, cols=2, print_grid=False,
    subplot_titles=['Number of Donations', "Total Donated Amount", 'Average Amount Per Donor (Min 10 Donations)', 'Maximum Single Donated Amount']
)
fig.append_trace(tr1, 1, 1)
fig.append_trace(tr2, 1, 2)
fig.append_trace(tr3, 2, 1)
fig.append_trace(tr4, 2, 2)

fig['layout'].update(
    height=600, showlegend=False,
    title='Top Projects and their - Total Donations, Total Amount, Amount Per Donor, Maximum Single Amount'
)

display(HTML(fig.to_html(include_plotlyjs="cdn", full_html=False)))

NameError: name 'bar_ver_noagg' is not defined

> - **Mejores Proyectos**
> - En la historia de donorschoose, diferentes proyectos recibieron un número variado de donaciones que va desde tan bajo como 1 hasta tan alto como 800 donaciones. El número máximo de donaciones realizado en un proyecto es igual a 863. Este fue un proyecto dirigido por un maestro y su título fue "**Vallecito StandUpKids Pilot Standing School!**" (mostrado como Pa1 en el primer gráfico). El monto total igual a **USD 108248.30** fue financiado en este proyecto y fue completamente financiado el 26 de agosto de 2015.
> - Hay otros tres proyectos con un número muy grande de donaciones (mayor que 600)
> - En noviembre de 2016, se inició un proyecto titulado "**Varsity and After-School Fencing Teams in NYC**" (mostrado como Pc1 en el segundo gráfico) y había 18 donaciones totales. Este proyecto tuvo el monto promedio más alto por donante igual a **USD 1850**
> - En el proyecto titulado "**Learning to Play While Playing to Learn!**" (mostrado como Pd1 en el cuarto gráfico), el monto de donación individual más alto igual a **USD 60,000** fue donado, que es el monto de donación individual más alto en la historia de DonorsChoose.

## <a id="3.3">3.3 Quiénes son los Donantes Principales:</a>

Identifiquemos donantes que han hecho algunas contribuciones principales y sus valores. Es decir:
- 3.3.1 Donantes que Han Realizado el Mayor Número de Donaciones
- 3.3.2 Donantes que Han Financiado los Mayores Montos Totales
- 3.3.3 Donantes que Financian Mayores Montos Promedio en Donaciones Individuales
- 3.3.4 Donantes que Han Financiado el Mayor Monto de Donación Individual

In [ ]:
# Which Projects Had the maximum Donations 

tempdf = donations_df.groupby('Donor ID').agg({
    'Donor ID': 'count',
    'Donation Amount': 'sum'
}).rename(columns={'Donor ID': "Total Donations", 'Donation Amount': "Total Amount"}).reset_index()

tempdf['Average Donation Amount'] = tempdf['Total Amount'] / tempdf['Total Donations']

tempdf1 = tempdf.sort_values(by=['Total Donations'], ascending=[False])
x = ["D" + str(i + 1) for i in range(5)]
y = tempdf1.head(5)['Total Donations']
tr1 = bar_ver_noagg(x, y, 'Total Donations', '#d141ea', lm=None, rt=True)

tempdf1 = tempdf.sort_values(by=['Total Amount'], ascending=[False])
x = ["D" + str(i + 1) for i in range(5)]
y = tempdf1.head(5)['Total Amount']
tr2 = bar_ver_noagg(x, y, 'Average Donations', '#db85ea', lm=None, rt=True)

tempdf1 = tempdf.sort_values(by=['Average Donation Amount'], ascending=[False])
x = ["D" + str(i + 1) for i in range(5)]
y = tempdf1.head(5)['Average Donation Amount']
tr3 = bar_ver_noagg(x, y, 'Average Donations', '#d5b1db', lm=None, rt=True)

tempdf = donations_df.groupby('Donor ID').agg({
    'Donor ID': 'count',
    'Donation Amount': 'max'
}).rename(columns={'Donor ID': "Total Donations", 'Donation Amount': "Maximum Donations"}).reset_index()

tempdf1 = tempdf.sort_values(by=['Maximum Donations'], ascending=[False])
x = ["D" + str(i + 1) for i in range(5)]
y = tempdf1.head(5)['Maximum Donations']
tr4 = bar_ver_noagg(x, y, 'Maximum Donations', '#ccbece', lm=None, rt=True)

fig = tools.make_subplots(
    rows=2, cols=2, print_grid=False,
    subplot_titles=['Number of Donations', "Total Donated Amount", 'Average Donated Amount', 'Maximum Donated Amount']
)
fig.append_trace(tr1, 1, 1)
fig.append_trace(tr2, 1, 2)
fig.append_trace(tr3, 2, 1)
fig.append_trace(tr4, 2, 2)

fig['layout'].update(
    height=600,
    showlegend=False,
    title='Top Donors and their Top Contributions'
)

display(HTML(fig.to_html(include_plotlyjs="cdn", full_html=False)))

> - **Donantes Más Generosos:**
> - Un donante no maestro de **Manhattan Beach, California** ha donado más de **18,000 veces** (mostrado como D1 en la esquina superior izquierda) en donorschoose. Otro donante no maestro de Nueva York ha donado una cantidad masiva igual a **1.8 M USD** en aproximadamente 10,513 donaciones (mostrado como D1 en la esquina superior derecha).
> - El pago individual más alto de **60K** para el proyecto "Learning to Play while Playing to Learn" fue realizado por un donante de **Anahola, Hawaii** e ha realizado un total de 223 donaciones hasta ahora.

## <a id="3.4">3.4 ¿Qué Montos de Donación se Recibieron en Qué Tiempos?</a>

### Donaciones por Año
- 3.4.1 Número de Donaciones por Año
- 3.4.2 Montos Promedio de Donación por Año

In [ ]:
donations_df['Donation Date'] = pd.to_datetime(donations_df['Donation Received Date'])
donations_df['Donation Year'] = donations_df['Donation Date'].dt.year
donations_df['Donation Month'] = donations_df['Donation Date'].dt.month
donations_df['Donation Day'] = donations_df['Donation Date'].dt.day
donations_df['Donation Weekday'] = donations_df['Donation Date'].dt.weekday
donations_df['Donation Hour'] = donations_df['Donation Date'].dt.hour

t1 = donations_df.groupby(['Donation Year']).agg({
    'Donation Month': 'count',
    'Donation Amount': 'mean'
}).reset_index().rename(columns={
    'Donation Month': 'Total Donations',
    'Donation Amount': 'Average Amount'
})

x = t1['Donation Year']
y1 = t1['Total Donations']
y2 = t1['Average Amount']

trace1 = go.Scatter(x=x[:-1], y=y1[:-1], fill='tozeroy', fillcolor='#fcc45f', mode='none')
trace2 = go.Scatter(x=x[:-1], y=y2[:-1], fill='tozeroy', fillcolor='#e993f9', mode='none')

fig = tools.make_subplots(
    rows=1, cols=2, print_grid=False,
    subplot_titles=["<b>Donations per Year</b>", "<b>Average Donation Amount per Year</b>"]
)
fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 2)

fig['layout'].update(
    height=300,
    showlegend=False,
    yaxis=dict(
        autorange=True, showgrid=False, zeroline=False,
        showline=False, ticks='', showticklabels=False
    ),
    yaxis2=dict(
        autorange=True, showgrid=False, zeroline=False,
        showline=False, ticks='', showticklabels=False
    )
)

display(HTML(fig.to_html(include_plotlyjs='cdn', full_html=False)))

> Desde el año 2012, el número de donaciones en donorschoose está aumentando regularmente. Con aproximadamente 150 donaciones recibidas en 2012, donorschoose recibió aproximadamente **1.1 Millón de donaciones** en el año 2017. El monto más alto recibido en 2017 fue igual a **USD 31856** que fue recibido de un donante de **Lafayette, Colorado**. Esta donación fue recibida el 02 de marzo de 2017.
> En el mismo año, un número gigantesco de donaciones fue recibido de un donante de **Manhattan Beach, California** quien donó **13751 donaciones**.
> El monto promedio de donación recibido por año es cercano a **USD 60**, mientras que fue más alto en el año inicial, es decir 2012, igual a **USD 166**.

### Donaciones por Mes
- 3.4.3 Número de Donaciones por Mes
- 3.4.4 Montos Promedio de Donación por Mes

In [ ]:
t2 = donations_df.groupby(['Donation Month']).agg({
    'Donation Year': 'count',
    'Donation Amount': 'mean'
}).reset_index().rename(columns={
    'Donation Year': 'Total Donations',
    'Donation Amount': 'Average Amount'
})

x = t2['Donation Month']
y1 = t2['Total Donations']
y2 = t2['Average Amount']

trace1 = go.Scatter(x=x, y=y1, fill='tozeroy', fillcolor='#fcc45f', mode='none')
trace2 = go.Scatter(x=x, y=y2, fill='tozeroy', fillcolor='#e993f9', mode='none')

fig = tools.make_subplots(
    rows=1, cols=2, print_grid=False,
    subplot_titles=["<b>Donations per Month</b>", "<b>Average Donation Amount per Month</b>"]
)
fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 2)

fig['layout'].update(
    height=300,
    showlegend=False,
    yaxis=dict(autorange=True, showgrid=False, zeroline=False, showline=False, ticks='', showticklabels=False),
    yaxis2=dict(autorange=True, showgrid=False, zeroline=False, showline=False, ticks='', showticklabels=False)
)

display(HTML(fig.to_html(include_plotlyjs="cdn", full_html=False)))

> - El mayor número de donaciones se recibe en el mes de **Agosto con 577,274 Donaciones** seguido de **Septiembre con 518,908 donaciones** mientras que el menor número de donaciones se recibe en el mes de **Junio igual a 191,221 donaciones** y mes de **Mayo igual a 243,440 donaciones**. Probablemente el tiempo de verano y vacaciones. El monto promedio de donación más alto se recibe en el mes de **Diciembre con USD 80** mientras que el menor es en el mes de **Julio igual a USD 51**. En promedio, el monto promedio de donación por año es cercano a USD 59.

### Donaciones por Día del Mes
- 3.4.5 Número de Donaciones por Día del Mes
- 3.4.6 Montos Promedio de Donación por Día del Mes

In [29]:
t3 = donations_df.groupby(['Donation Day']).agg({'Donation Year' : 'count', 'Donation Amount' : 'mean'}).reset_index().rename(columns={'Donation Year' : 'Total Donations', 'Donation Amount' : 'Average Amount'})
x = t3['Donation Day']
y1 = t3['Total Donations']
y2 = t3['Average Amount']
trace1 = go.Scatter(x=x, y=y1, fill='tozeroy', fillcolor = '#fcc45f', mode= 'none')
trace2 = go.Scatter(x=x, y=y2, fill='tozeroy', fillcolor = "#e993f9", mode= 'none')
fig = tools.make_subplots(rows=1, cols=2, print_grid=False, subplot_titles = ["<b>Donations per MonthDay</b>", "<b>Average Donation Amount per MonthDay</b>"])
fig.append_trace(trace1, 1, 1);
fig.append_trace(trace2, 1, 2);

fig['layout'].update(height=300, showlegend=False, yaxis=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        ticks='',
        showticklabels=False
    ), yaxis2=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        ticks='',
        showticklabels=False
    ));
iplot(fig);

KeyError: 'Donation Day'

### Donaciones por Día de Semana
- 3.4.7 Número de Donaciones por Día de Semana
- 3.4.8 Montos Promedio de Donación por Día de Semana

In [ ]:
t4 = donations_df.groupby(['Donation Weekday']).agg({'Donation Year' : 'count', 'Donation Amount' : 'mean'}).reset_index().rename(columns={'Donation Year' : 'Total Donations', 'Donation Amount' : 'Average Amount'})
x = t4['Donation Weekday']
y1 = t4['Total Donations']
y2 = t4['Average Amount']
trace1 = go.Scatter(x=x, y=y1, fill='tozeroy', fillcolor = '#fcc45f', mode= 'none')
trace2 = go.Scatter(x=x, y=y2, fill='tozeroy', fillcolor = "#e993f9", mode= 'none')
fig = tools.make_subplots(rows=1, cols=2, print_grid=False, subplot_titles = ["<b>Donations per WeekDay</b>", "<b>Average Donation Amount per WeekDay</b>"])
fig.append_trace(trace1, 1, 1);
fig.append_trace(trace2, 1, 2);

fig['layout'].update(height=300, showlegend=False, yaxis=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        ticks='',
        showticklabels=False
    ), yaxis2=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        ticks='',
        showticklabels=False
    ));
iplot(fig);

ValueError: Invalid property specified for object of type plotly.graph_objs.layout.YAxis: 'autotick'

Did you mean "autoshift"?

    Valid properties:
        anchor
            If set to an opposite-letter axis id (e.g. `x2`, `y`),
            this axis is bound to the corresponding opposite-letter
            axis. If set to "free", this axis' position is
            determined by `position`.
        automargin
            Determines whether long tick labels automatically grow
            the figure margins.
        autorange
            Determines whether or not the range of this axis is
            computed in relation to the input data. See `rangemode`
            for more info. If `range` is provided and it has a
            value for both the lower and upper bound, `autorange`
            is set to False. Using "min" applies autorange only to
            set the minimum. Using "max" applies autorange only to
            set the maximum. Using *min reversed* applies autorange
            only to set the minimum on a reversed axis. Using *max
            reversed* applies autorange only to set the maximum on
            a reversed axis. Using "reversed" applies autorange on
            both ends and reverses the axis direction.
        autorangeoptions
            :class:`plotly.graph_objects.layout.yaxis.Autorangeopti
            ons` instance or dict with compatible properties
        autoshift
            Automatically reposition the axis to avoid overlap with
            other axes with the same `overlaying` value. This
            repositioning will account for any `shift` amount
            applied to other axes on the same side with `autoshift`
            is set to true. Only has an effect if `anchor` is set
            to "free".
        autotickangles
            When `tickangle` is set to "auto", it will be set to
            the first angle in this array that is large enough to
            prevent label overlap.
        autotypenumbers
            Using "strict" a numeric string in trace data is not
            converted to a number. Using *convert types* a numeric
            string in trace data may be treated as a number during
            automatic axis `type` detection. Defaults to
            layout.autotypenumbers.
        calendar
            Sets the calendar system to use for `range` and `tick0`
            if this is a date axis. This does not set the calendar
            for interpreting data on this axis, that's specified in
            the trace or via the global `layout.calendar`
        categoryarray
            Sets the order in which categories on this axis appear.
            Only has an effect if `categoryorder` is set to
            "array". Used with `categoryorder`.
        categoryarraysrc
            Sets the source reference on Chart Studio Cloud for
            `categoryarray`.
        categoryorder
            Specifies the ordering logic for the case of
            categorical variables. By default, plotly uses "trace",
            which specifies the order that is present in the data
            supplied. Set `categoryorder` to *category ascending*
            or *category descending* if order should be determined
            by the alphanumerical order of the category names. Set
            `categoryorder` to "array" to derive the ordering from
            the attribute `categoryarray`. If a category is not
            found in the `categoryarray` array, the sorting
            behavior for that attribute will be identical to the
            "trace" mode. The unspecified categories will follow
            the categories in `categoryarray`. Set `categoryorder`
            to *total ascending* or *total descending* if order
            should be determined by the numerical order of the
            values. Similarly, the order can be determined by the
            min, max, sum, mean, geometric mean or median of all
            the values.
        color
            Sets default for all colors associated with this axis
            all at once: line, font, tick, and grid colors. Grid
            color is lightened by blending this with the plot
            background Individual pieces can override this.
        constrain
            If this axis needs to be compressed (either due to its
            own `scaleanchor` and `scaleratio` or those of the
            other axis), determines how that happens: by increasing
            the "range", or by decreasing the "domain". Default is
            "domain" for axes containing image traces, "range"
            otherwise.
        constraintoward
            If this axis needs to be compressed (either due to its
            own `scaleanchor` and `scaleratio` or those of the
            other axis), determines which direction we push the
            originally specified plot area. Options are "left",
            "center" (default), and "right" for x axes, and "top",
            "middle" (default), and "bottom" for y axes.
        dividercolor
            Sets the color of the dividers Only has an effect on
            "multicategory" axes.
        dividerwidth
            Sets the width (in px) of the dividers Only has an
            effect on "multicategory" axes.
        domain
            Sets the domain of this axis (in plot fraction).
        dtick
            Sets the step in-between ticks on this axis. Use with
            `tick0`. Must be a positive number, or special strings
            available to "log" and "date" axes. If the axis `type`
            is "log", then ticks are set every 10^(n*dtick) where n
            is the tick number. For example, to set a tick mark at
            1, 10, 100, 1000, ... set dtick to 1. To set tick marks
            at 1, 100, 10000, ... set dtick to 2. To set tick marks
            at 1, 5, 25, 125, 625, 3125, ... set dtick to
            log_10(5), or 0.69897000433. "log" has several special
            values; "L<f>", where `f` is a positive number, gives
            ticks linearly spaced in value (but not position). For
            example `tick0` = 0.1, `dtick` = "L0.5" will put ticks
            at 0.1, 0.6, 1.1, 1.6 etc. To show powers of 10 plus
            small digits between, use "D1" (all digits) or "D2"
            (only 2 and 5). `tick0` is ignored for "D1" and "D2".
            If the axis `type` is "date", then you must convert the
            time to milliseconds. For example, to set the interval
            between ticks to one day, set `dtick` to 86400000.0.
            "date" also has special values "M<n>" gives ticks
            spaced by a number of months. `n` must be a positive
            integer. To set ticks on the 15th of every third month,
            set `tick0` to "2000-01-15" and `dtick` to "M3". To set
            ticks every 4 years, set `dtick` to "M48"
        exponentformat
            Determines a formatting rule for the tick exponents.
            For example, consider the number 1,000,000,000. If
            "none", it appears as 1,000,000,000. If "e", 1e+9. If
            "E", 1E+9. If "power", 1x10^9 (with 9 in a super
            script). If "SI", 1G. If "B", 1B. "SI" uses prefixes
            from "femto" f (10^-15) to "tera" T (10^12). *SI
            extended* covers instead the full SI range from
            "quecto" q (10^-30) to "quetta" Q (10^30). If "SI" or
            *SI extended* is used and the exponent is beyond the
            above ranges, the formatting rule will automatically be
            switched to the power notation.
        fixedrange
            Determines whether or not this axis is zoom-able. If
            true, then zoom is disabled.
        gridcolor
            Sets the color of the grid lines.
        griddash
            Sets the dash style of lines. Set to a dash type string
            ("solid", "dot", "dash", "longdash", "dashdot", or
            "longdashdot") or a dash length list in px (eg
            "5px,10px,2px,2px").
        gridwidth
            Sets the width (in px) of the grid lines.
        hoverformat
            Sets the hover text formatting rule using d3 formatting
            mini-languages which are very similar to those in
            Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display "09~15~23.46"
        insiderange
            Could be used to set the desired inside range of this
            axis (excluding the labels) when `ticklabelposition` of
            the anchored axis has "inside". Not implemented for
            axes with `type` "log". This would be ignored when
            `range` is provided.
        labelalias
            Replacement text for specific tick or hover labels. For
            example using {US: 'USA', CA: 'Canada'} changes US to
            USA and CA to Canada. The labels we would have shown
            must match the keys exactly, after adding any
            tickprefix or ticksuffix. For negative numbers the
            minus sign symbol used (U+2212) is wider than the
            regular ascii dash. That means you need to use −1
            instead of -1. labelalias can be used with any axis
            type, and both keys (if needed) and values (if desired)
            can include html-like tags or MathJax.
        layer
            Sets the layer on which this axis is displayed. If
            *above traces*, this axis is displayed above all the
            subplot's traces If *below traces*, this axis is
            displayed below all the subplot's traces, but above the
            grid lines. Useful when used together with scatter-like
            traces with `cliponaxis` set to False to show markers
            and/or text nodes above this axis.
        linecolor
            Sets the axis line color.
        linewidth
            Sets the width (in px) of the axis line.
        matches
            If set to another axis id (e.g. `x2`, `y`), the range
            of this axis will match the range of the corresponding
            axis in data-coordinates space. Moreover, matching axes
            share auto-range values, category lists and histogram
            auto-bins. Note that setting axes simultaneously in
            both a `scaleanchor` and a `matches` constraint is
            currently forbidden. Moreover, note that matching axes
            must have the same `type`.
        maxallowed
            Determines the maximum range of this axis.
        minallowed
            Determines the minimum range of this axis.
        minexponent
            Hide SI prefix for 10^n if |n| is below this number.
            This only has an effect when `tickformat` is "SI" or
            "B".
        minor
            :class:`plotly.graph_objects.layout.yaxis.Minor`
            instance or dict with compatible properties
        minorloglabels
            Determines how minor log labels are displayed. If
            *small digits*, small digits i.e. 2 or 5 are displayed.
            If "complete", complete digits are displayed. If
            "none", no labels are displayed.
        mirror
            Determines if the axis lines or/and ticks are mirrored
            to the opposite side of the plotting area. If True, the
            axis lines are mirrored. If "ticks", the axis lines and
            ticks are mirrored. If False, mirroring is disable. If
            "all", axis lines are mirrored on all shared-axes
            subplots. If "allticks", axis lines and ticks are
            mirrored on all shared-axes subplots.
        modebardisable
            Disables certain modebar buttons for this axis.
            "autoscale" disables the autoscale buttons, "zoominout"
            disables the zoom-in and zoom-out buttons.
        nticks
            Specifies the maximum number of ticks for the
            particular axis. The actual number of ticks will be
            chosen automatically to be less than or equal to
            `nticks`. Has an effect only if `tickmode` is set to
            "auto".
        overlaying
            If set a same-letter axis id, this axis is overlaid on
            top of the corresponding same-letter axis, with traces
            and axes visible for both axes. If False, this axis
            does not overlay any same-letter axes. In this case,
            for axes with overlapping domains only the highest-
            numbered axis will be visible.
        position
            Sets the position of this axis in the plotting space
            (in normalized coordinates). Only has an effect if
            `anchor` is set to "free".
        range
            Sets the range of this axis. If the axis `type` is
            "log", then you must take the log of your desired range
            (e.g. to set the range from 1 to 100, set the range
            from 0 to 2). If the axis `type` is "date", it should
            be date strings, like date data, though Date objects
            and unix milliseconds will be accepted and converted to
            strings. If the axis `type` is "category", it should be
            numbers, using the scale where each category is
            assigned a serial number from zero in the order it
            appears. Leaving either or both elements `null` impacts
            the default `autorange`.
        rangebreaks
            A tuple of
            :class:`plotly.graph_objects.layout.yaxis.Rangebreak`
            instances or dicts with compatible properties
        rangebreakdefaults
            When used in a template (as
            layout.template.layout.yaxis.rangebreakdefaults), sets
            the default property values to use for elements of
            layout.yaxis.rangebreaks
        rangemode
            If "normal", the range is computed in relation to the
            extrema of the input data. If "tozero", the range
            extends to 0, regardless of the input data If
            "nonnegative", the range is non-negative, regardless of
            the input data. Applies only to linear axes.
        scaleanchor
            If set to another axis id (e.g. `x2`, `y`), the range
            of this axis changes together with the range of the
            corresponding axis such that the scale of pixels per
            unit is in a constant ratio. Both axes are still
            zoomable, but when you zoom one, the other will zoom
            the same amount, keeping a fixed midpoint. `constrain`
            and `constraintoward` determine how we enforce the
            constraint. You can chain these, ie `yaxis:
            {scaleanchor: *x*}, xaxis2: {scaleanchor: *y*}` but you
            can only link axes of the same `type`. The linked axis
            can have the opposite letter (to constrain the aspect
            ratio) or the same letter (to match scales across
            subplots). Loops (`yaxis: {scaleanchor: *x*}, xaxis:
            {scaleanchor: *y*}` or longer) are redundant and the
            last constraint encountered will be ignored to avoid
            possible inconsistent constraints via `scaleratio`.
            Note that setting axes simultaneously in both a
            `scaleanchor` and a `matches` constraint is currently
            forbidden. Setting `false` allows to remove a default
            constraint (occasionally, you may need to prevent a
            default `scaleanchor` constraint from being applied,
            eg. when having an image trace `yaxis: {scaleanchor:
            "x"}` is set automatically in order for pixels to be
            rendered as squares, setting `yaxis: {scaleanchor:
            false}` allows to remove the constraint).
        scaleratio
            If this axis is linked to another by `scaleanchor`,
            this determines the pixel to unit scale ratio. For
            example, if this value is 10, then every unit on this
            axis spans 10 times the number of pixels as a unit on
            the linked axis. Use this for example to create an
            elevation profile where the vertical scale is
            exaggerated a fixed amount with respect to the
            horizontal.
        separatethousands
            If "true", even 4-digit integers are separated
        shift
            Moves the axis a given number of pixels from where it
            would have been otherwise. Accepts both positive and
            negative values, which will shift the axis either right
            or left, respectively. If `autoshift` is set to true,
            then this defaults to a padding of -3 if `side` is set
            to "left". and defaults to +3 if `side` is set to
            "right". Defaults to 0 if `autoshift` is set to false.
            Only has an effect if `anchor` is set to "free".
        showdividers
            Determines whether or not a dividers are drawn between
            the category levels of this axis. Only has an effect on
            "multicategory" axes.
        showexponent
            If "all", all exponents are shown besides their
            significands. If "first", only the exponent of the
            first tick is shown. If "last", only the exponent of
            the last tick is shown. If "none", no exponents appear.
        showgrid
            Determines whether or not grid lines are drawn. If
            True, the grid lines are drawn at every tick mark.
        showline
            Determines whether or not a line bounding this axis is
            drawn.
        showspikes
            Determines whether or not spikes (aka droplines) are
            drawn for this axis. Note: This only takes affect when
            hovermode = closest
        showticklabels
            Determines whether or not the tick labels are drawn.
        showtickprefix
            If "all", all tick labels are displayed with a prefix.
            If "first", only the first tick is displayed with a
            prefix. If "last", only the last tick is displayed with
            a suffix. If "none", tick prefixes are hidden.
        showticksuffix
            Same as `showtickprefix` but for tick suffixes.
        side
            Determines whether a x (y) axis is positioned at the
            "bottom" ("left") or "top" ("right") of the plotting
            area.
        spikecolor
            Sets the spike color. If undefined, will use the series
            color
        spikedash
            Sets the dash style of lines. Set to a dash type string
            ("solid", "dot", "dash", "longdash", "dashdot", or
            "longdashdot") or a dash length list in px (eg
            "5px,10px,2px,2px").
        spikemode
            Determines the drawing mode for the spike line If
            "toaxis", the line is drawn from the data point to the
            axis the  series is plotted on. If "across", the line
            is drawn across the entire plot area, and supercedes
            "toaxis". If "marker", then a marker dot is drawn on
            the axis the series is plotted on
        spikesnap
            Determines whether spikelines are stuck to the cursor
            or to the closest datapoints.
        spikethickness
            Sets the width (in px) of the zero line.
        tick0
            Sets the placement of the first tick on this axis. Use
            with `dtick`. If the axis `type` is "log", then you
            must take the log of your starting tick (e.g. to set
            the starting tick to 100, set the `tick0` to 2) except
            when `dtick`=*L<f>* (see `dtick` for more info). If the

> El número de donaciones es más alto en los primeros días de la semana, es decir lunes, martes y miércoles con 700K, 800K, 750K donaciones totales y la cuenta disminuye con los siguientes días de la semana. El número más bajo de donaciones se recibe los sábados como se observa en el gráfico.

### Donaciones por Hora
- 3.4.9 Número de Donaciones por Hora
- 3.4.10 Montos Promedio de Donación por Hora

In [ ]:
t5 = donations_df.groupby(['Donation Hour']).agg({'Donation Month' : 'count', 'Donation Amount' : 'mean'}).reset_index().rename(columns={'Donation Month' : 'Total Donations', 'Donation Amount' : 'Average Amount'})
x = t5['Donation Hour']
y1 = t5['Total Donations']
y2 = t5['Average Amount']
trace1 = go.Scatter(x=x[:-1], y=y1[:-1], fill='tozeroy', fillcolor = '#fcc45f', mode= 'none')
trace2 = go.Scatter(x=x[:-1], y=y2[:-1], fill='tozeroy', fillcolor = "#e993f9", mode= 'none')
fig = tools.make_subplots(rows=1, cols=2, print_grid=False, subplot_titles = ["<b>Donations per Hour</b>", "<b>Average Donation Amount per Hour</b>"])
fig.append_trace(trace1, 1, 1);
fig.append_trace(trace2, 1, 2);

fig['layout'].update(height=300, showlegend=False, yaxis=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        autotick=True,
        ticks='',
        showticklabels=False
    ), yaxis2=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        autotick=True,
        ticks='',
        showticklabels=False
    ));
iplot(fig);

## <a id="3.5">3.5 Donaciones Opcionales y Donaciones de Donantes Maestros</a>

### <a id="3.5.1">3.5.1 Total de Donaciones Opcionales y sus Montos Promedio Asociados</a>

In [ ]:
tempdf = donations_df.groupby('Donation Included Optional Donation').agg({'Donation Included Optional Donation' : 'count', 'Donation Amount' : 'mean'})
values1 = list(tempdf['Donation Included Optional Donation']) 
values2 = list(tempdf['Donation Amount']) 
values2t = [str("$")+str(int(x)) for x in values2]
domain1 = {'x': [0.2, 0.50], 'y': [0.0, 0.33]}
domain2 = {'x': [0.8, 0.50], 'y': [0.0, 0.33]}

labels = list(tempdf.index)
mp={'Yes' : 'Optional Donations', 'No' : 'No Optional Donations'}
labels = [mp[x] for x in labels]
trace1 = go.Pie(labels=labels, values=values1, marker=dict(colors=[  '#75e575', '#ea7c96',]))
trace2 = go.Pie(labels=labels, values=values2, marker=dict(colors=['#75e575', '#ea7c96',]), textinfo = "text", text=values2t)

layout = go.Layout(title='Number of Donations with Optional Donations', width=800, height=400)
# fig = go.Figure(data=[trace1], layout=layout)
# iplot(fig)

layout = go.Layout(title='Average Amount Donated in Optional Donations', width=800, height=400)
# fig = go.Figure(data=[trace2], layout=layout)
# iplot(fig)

fig = {
  "data": [
    {
      "values": values1,
      "labels": list(reversed(labels)),
      "domain": {"x": [0, .48]},
    "marker" : dict(colors=[  '#f9345b',  '#75e575']),
      "name": "No. of donations with Optional Donations",
#       "hoverinfo":"label+percent+name",
#       "hole": .4,
        
      "type": "pie"
    },
    {
      "values": values2,
      "labels": labels,
        "marker" : dict(colors=['75e575', '#f9345b']),
      "domain": {"x": [.52, 1]},
      "name": "Average Amount Donated in Optional Donations",
        "text" : values2t,
        "textinfo" : "text",
      "type": "pie"
    }],
  "layout": {
        "title":"Optional Donations : Total Count and Average Donation Amount",
    
    }
}
iplot(fig, filename='donut')

> - Los proyectos de DonorChoose también tienen la opción de Donaciones Opcionales. El monto promedio de donación para donación opcional es **USD 58** mientras que es **USD 73** para donación no opcional. De todas las donaciones realizadas, aproximadamente **15%** de ellas fueron donaciones opcionales.

### <a href="3.5.2">3.5.2 Total de Donaciones de Donantes Maestros y los Montos Promedio Asociados</a>

In [ ]:
# lets combine donors and donations 
combined_df = donations_df.merge(donors_df, on='Donor ID', how='inner')
# combined_df.head(10)

tempdf = combined_df.groupby('Donor Is Teacher').agg({'Donor Is Teacher' : 'count', 'Donation Amount' : 'mean'})
values1 = list(tempdf['Donor Is Teacher']) 
values2 = list(tempdf['Donation Amount']) 
values2t = [str("$")+str(int(x)) for x in values2]
domain1 = {'x': [0.2, 0.50], 'y': [0.0, 0.33]}
domain2 = {'x': [0.8, 0.50], 'y': [0.0, 0.33]}

labels = list(tempdf.index)
mp={'Yes' : 'Teacher Donor', 'No' : 'Non Teacher Donor'}
labels = [mp[x] for x in labels]
trace1 = go.Pie(labels=labels, values=values1, marker=dict(colors=[  '#75e575', '#ea7c96',]))
trace2 = go.Pie(labels=labels, values=values2, marker=dict(colors=['#75e575', '#ea7c96',]), textinfo = "text", text=values2t)

layout = go.Layout(title='Number of Donations with Optional Donations', width=800, height=400)
# fig = go.Figure(data=[trace1], layout=layout)
# iplot(fig)

layout = go.Layout(title='Average Amount Donated in Optional Donations', width=800, height=400)
# fig = go.Figure(data=[trace2], layout=layout)
# iplot(fig)

fig = {
  "data": [
    {
      "values": values1,
      "labels": labels,
      "domain": {"x": [0, .48]},
    "marker" : dict(colors=[ '#ab97db',  '#b0b1b2']),
      "name": "No. of donations with Optional Donations",
#       "hoverinfo":"label+percent+name",
#       "hole": .4,
        
      "type": "pie"
    },
    {
      "values": values2,
      "labels": labels,
        "marker" : dict(colors=[ '#ab97db',  '#b0b1b2']),
      "domain": {"x": [.52, 1]},
      "name": "Average Amount Donated in Optional Donations",
        "text" : values2t,
        "textinfo" : "text",
      "type": "pie"
    }],
  "layout": {
        "title":"Optional Donations : Total Count and Average Donation Amount",
    
    }
}
iplot(fig, filename='donut')

> - Aproximadamente **29%** del total de donaciones en DonorChoose son realizadas por Donantes que también son maestros. La mayoría de tales DonantesProfesor son de California.
> - El monto promedio de donación de maestro es **USD 45** mientras que es **USD 66** para donantes no maestros.

In [ ]:

def mapp(df, scl, t):
    state_to_code = {'District of Columbia' : 'dc','Mississippi': 'MS', 'Oklahoma': 'OK', 'Delaware': 'DE', 'Minnesota': 'MN', 'Illinois': 'IL', 'Arkansas': 'AR', 'New Mexico': 'NM', 'Indiana': 'IN', 'Maryland': 'MD', 'Louisiana': 'LA', 'Idaho': 'ID', 'Wyoming': 'WY', 'Tennessee': 'TN', 'Arizona': 'AZ', 'Iowa': 'IA', 'Michigan': 'MI', 'Kansas': 'KS', 'Utah': 'UT', 'Virginia': 'VA', 'Oregon': 'OR', 'Connecticut': 'CT', 'Montana': 'MT', 'California': 'CA', 'Massachusetts': 'MA', 'West Virginia': 'WV', 'South Carolina': 'SC', 'New Hampshire': 'NH', 'Wisconsin': 'WI', 'Vermont': 'VT', 'Georgia': 'GA', 'North Dakota': 'ND', 'Pennsylvania': 'PA', 'Florida': 'FL', 'Alaska': 'AK', 'Kentucky': 'KY', 'Hawaii': 'HI', 'Nebraska': 'NE', 'Missouri': 'MO', 'Ohio': 'OH', 'Alabama': 'AL', 'Rhode Island': 'RI', 'South Dakota': 'SD', 'Colorado': 'CO', 'New Jersey': 'NJ', 'Washington': 'WA', 'North Carolina': 'NC', 'New York': 'NY', 'Texas': 'TX', 'Nevada': 'NV', 'Maine': 'ME'}
    df['state_code'] = statesdf['state'].apply(lambda x : state_to_code[x] if x in state_to_code else "")

    data = [ dict(
            type='choropleth',
            colorscale = scl,
            autocolorscale = False,
            locations = df['state_code'],
            z = df['counts'],
            locationmode = 'USA-states',
            text = df['state'],
            marker = dict(
                line = dict (
                    color = 'rgb(255,255,255)',
                    width = 2
                ) ),
            colorbar = dict(
                title = "Donors")
            ) ]

    layout = dict(
            title = t,
            geo = dict(
                scope='usa',
                projection=dict( type='albers usa' ),
                showlakes = True,
                lakecolor = 'rgb(255, 255, 255)'),
                 )

    fig = dict( data=data, layout=layout )
    iplot( fig, filename='d3-cloropleth-map' )

## <a id="3.6">3.6 Qué Estados Recibieron los Mayores Montos de Donación Individual</a>
- 3.6.1 Estados Principales con Mayores Montos de Donación
- 3.6.2 Ciudades Principales con Mayores Montos de Donación

In [ ]:
# Maximum Donation Amounts 
tempdf = combined_df.groupby(['Donor State']).agg({'Donation Amount':'max'}).reset_index()
t1 = tempdf.sort_values('Donation Amount', ascending=False)

tempdf = combined_df.groupby(['Donor City']).agg({'Donation Amount':'max'}).reset_index()
t2 = tempdf.sort_values('Donation Amount', ascending=False)

statesdf = pd.DataFrame()
statesdf['state'] = t1['Donor State']
statesdf['counts'] = t1['Donation Amount']
statesdf

citydf = pd.DataFrame()
citydf['state'] = t2['Donor City']
citydf['counts'] = t2['Donation Amount']
citydf


scl = [[0.0, 'rgb(240,240,240)'],[0.2, 'rgb(220,220,220)'],[0.4, 'rgb(180,180,180)'], [0.6, 'rgb(154,154,154)'],[0.8, 'rgb(117,117,117)'],[1.0, 'rgb(84,84,84)']]
mapp(statesdf, scl, 'Maximum Single Donations by States')

trace1 = bar_hor_noagg(list(reversed(list(statesdf['state'][:10]))), list(reversed(list(statesdf['counts'][:10]))), "Top Cities with maximum Donors", '#a8a1a3', 600, 400, 200, limit = 10, rt=True)
trace2 = bar_hor_noagg(list(reversed(list(citydf['state'][:10]))), list(reversed(list(citydf['counts'][:10]))), "Top States with maximum Donors", '#a8a1a3', 600, 400, 200, limit = 10, rt=True)
fig = tools.make_subplots(rows=1, cols=2, print_grid=False, subplot_titles = ['Top States with Maximum Single Donation','Top Cities with maximum Single Donation'])
fig.append_trace(trace1, 1, 1);
fig.append_trace(trace2, 1, 2);
fig['layout'].update(height=400, showlegend=False);
iplot(fig);

> - Hawaii, Colorado son estados aunque con menos número de donaciones pero se reciben los mayores montos de donación desde allí.
> - Ciudades: Anahola, Lafayette y Palo Alto han contribuido a los mayores montos: 60K, 31K y 26K.

## <a id="3.7">3.7 Qué Estado Recibe los Mayores Montos de Donación Promedio</a>

In [ ]:
# Mean Donation Amounts 
tempdf = combined_df.groupby(['Donor State']).agg({'Donation Amount':'mean'}).reset_index()
t1 = tempdf.sort_values('Donation Amount', ascending=False)

tempdf = combined_df.groupby(['Donor City']).agg({'Donation Amount':'mean'}).reset_index()
t2 = tempdf.sort_values('Donation Amount', ascending=False)

statesdf = pd.DataFrame()
statesdf['state'] = t1['Donor State']
statesdf['counts'] = t1['Donation Amount']
statesdf

citydf = pd.DataFrame()
citydf['state'] = t2['Donor City']
citydf['counts'] = t2['Donation Amount']
citydf
scl = [[0.0, 'rgb(248,255,206)'],[0.2, 'rgb(203,255,205)'],[0.4, 'rgb(155,255,164)'], [0.6, 'rgb(79,255,178)'],[0.8, 'rgb(15,183,132)'], [1, '#008059']]
# scl = [[0.0, 'rgb(240,240,240)'],[0.2, 'rgb(220,220,220)'],[0.4, 'rgb(180,180,180)'], [0.6, 'rgb(154,154,154)'],[0.8, 'rgb(117,117,117)'],[1.0, 'rgb(84,84,84)']]
mapp(statesdf, scl, 'States Average Donation Amounts')

trace1 = bar_hor_noagg(list(reversed(list(statesdf['state'][:10]))), list(reversed(list(statesdf['counts'][:10]))), "Top Cities with maximum Donors", '#a8a1a3', 600, 400, 200, limit = 10, rt=True)
trace2 = bar_hor_noagg(list(reversed(list(citydf['state'][:10]))), list(reversed(list(citydf['counts'][:10]))), "Top States with maximum Donors", '#a8a1a3', 600, 400, 200, limit = 10, rt=True)
fig = tools.make_subplots(rows=1, cols=2, print_grid=False, subplot_titles = ['States and Average Donated Amounts','Cities and Average Donatied Amounts'])
fig.append_trace(trace1, 1, 1);
fig.append_trace(trace2, 1, 2);
fig['layout'].update(height=400, showlegend=False);
iplot(fig);

> - Hawaii y Massachusetts tienen los mayores montos promedio de donación.
> - Clarks Point, Swiftwater, North English son ciudades desde las cuales se reciben los mayores montos promedio de donación.

## <a id="3.8">3.8 Montos Totales Donados de Cada Estado</a>

In [ ]:
statesll=StringIO("""State,Latitude,Longitude
Alabama,32.806671,-86.791130
Alaska,61.370716,-152.404419
Arizona,33.729759,-111.431221
Arkansas,34.969704,-92.373123
California,36.116203,-119.681564
Colorado,39.059811,-105.311104
Connecticut,41.597782,-72.755371
Delaware,39.318523,-75.507141
District of Columbia,38.897438,-77.026817
Florida,27.766279,-81.686783
Georgia,33.040619,-83.643074
Hawaii,21.094318,-157.498337
Idaho,44.240459,-114.478828
Illinois,40.349457,-88.986137
Indiana,39.849426,-86.258278
Iowa,42.011539,-93.210526
Kansas,38.526600,-96.726486
Kentucky,37.668140,-84.670067
Louisiana,31.169546,-91.867805
Maine,44.693947,-69.381927
Maryland,39.063946,-76.802101
Massachusetts,42.230171,-71.530106
Michigan,43.326618,-84.536095
Minnesota,45.694454,-93.900192
Mississippi,32.741646,-89.678696
Missouri,38.456085,-92.288368
Montana,46.921925,-110.454353
Nebraska,41.125370,-98.268082
Nevada,38.313515,-117.055374
New Hampshire,43.452492,-71.563896
New Jersey,40.298904,-74.521011
New Mexico,34.840515,-106.248482
New York,42.165726,-74.948051
North Carolina,35.630066,-79.806419
North Dakota,47.528912,-99.784012
Ohio,40.388783,-82.764915
Oklahoma,35.565342,-96.928917
Oregon,44.572021,-122.070938
Pennsylvania,40.590752,-77.209755
Rhode Island,41.680893,-71.511780
South Carolina,33.856892,-80.945007
South Dakota,44.299782,-99.438828
Tennessee,35.747845,-86.692345
Texas,31.054487,-97.563461
Utah,40.150032,-111.862434
Vermont,44.045876,-72.710686
Virginia,37.769337,-78.169968
Washington,47.400902,-121.490494
West Virginia,38.491226,-80.954453
Wisconsin,44.268543,-89.616508
Wyoming,42.755966,-107.302490""")

tempdf = combined_df.groupby(['Donor State']).agg({'Donation Amount':'sum'}).reset_index()
t1 = tempdf.sort_values('Donation Amount', ascending=False)

sdf = pd.read_csv(statesll).rename(columns={'State':'Donor State'})
sdf = sdf.merge(t1, on='Donor State', how='inner')

map4 = folium.Map(location=[39.50, -98.35], tiles='CartoDB dark_matter', zoom_start=3.5)
for j, rown in sdf.iterrows():
    rown = list(rown)
    folium.CircleMarker([float(rown[1]), float(rown[2])], popup=rown[0]+": $"+str(int(rown[3])), radius=float(rown[3])*0.000001, color='blue', fill=True).add_to(map4)
map4

## <a id="3.9">3.9 Donaciones de California a lo Largo del Tiempo</a>

Veamos la tendencia de donaciones de California a lo largo de los años

In [ ]:
combined_df['Donation Date'] = combined_df['Donation Received Date'].apply(lambda x : str(x).split()[0])

cali = combined_df[combined_df['Donor State'] == 'California']
cali = cali.groupby('Donation Date').agg({'Donation Amount' : 'count'}).reset_index()
cali1 = pd.DataFrame()
cali1['Date'] = pd.to_datetime(cali['Donation Date']) 
cali1['Donation Amount'] = cali['Donation Amount']


trace1 = go.Scatter(x=cali1['Date'], y=cali1['Donation Amount'], name = "California", line = dict(color = 'red'), opacity = 0.8)

data = [trace1]
layout = dict(title="Donations from California over time", height=400, showlegend=False, yaxis=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        autotick=True,
        ticks='',
        showticklabels=False
    ))
fig = dict(data=data, layout=layout)
iplot(fig)

> El mayor número de donaciones de California llegó el **25 de enero de 2018** con casi 5000 donaciones seguido de **28 de noviembre de 2017** con 4699 donaciones.

## <a id="4">4. Exploración de Maestros</a>
## <a id="4.1">4.1 Descripción General de Datos de Maestros</a>

In [ ]:
teachers_df.head(3)
# len(teachers_df)

> Hay un total de **402,900** maestros que han publicado al menos un proyecto en donorschoose desde 2002. Una gran mayoría de maestros son mujeres. Veamos quiénes fueron los primeros maestros que publicaron proyectos en donorschoose.

## <a id="4.2">4.2 Quiénes Fueron los Primeros Maestros en DonorsChoose.org</a>

In [ ]:
teachers_df['Posted Date'] = pd.to_datetime(teachers_df['Teacher First Project Posted Date'])
teachers_df['Posted Year'] = teachers_df['Posted Date'].dt.year

# Lets Find out who were the first donors on DonorsChooseSome of the Earliest Teachers 
teachers_df[['Teacher ID', 'Posted Date']].sort_values(['Posted Date'])[:10]

> Los primeros maestros en DonorsChoose se registraron el 2002-09-17. En ese día se registraron 2 maestros, ambas mujeres. En el mes de septiembre de 2002, se registraron 8 maestros en total que fueron principalmente el primer grupo de maestros en donorschoose.

## <a id="4.3">4.3 Crecimiento en el Número de Maestros a lo Largo de los Años</a>

In [ ]:
temp = teachers_df.groupby('Posted Year').agg({'Teacher ID' : 'count'}).reset_index()
temp = temp.sort_values('Posted Year')

trace = go.Scatter(
        x=list(temp['Posted Year'])[:-1],
        y=list(temp['Teacher ID'])[:-1],
        mode='lines+marker',
        line=dict(color="#42e5f4", width=8),
        connectgaps=True,
    fillcolor='rgba(0,100,80,0.2)',
    )

layout = go.Layout(
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        autotick=False,
        ticks='outside',
        tickcolor='rgb(204, 204, 204)',
        tickwidth=2,
        ticklen=5,
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    ),
    title = 'Year wise Number of Teachers who started posting their projects')



fig = go.Figure(data=[trace], layout=layout)
iplot(fig, filename='news-source')

> - El número de maestros comenzó a publicar en DonorChoose cuando fue lanzado en 2002, pero los primeros cinco años vieron muy pocos maestros publicando los proyectos.
>> - Una tendencia creciente comenzó a desarrollarse alrededor de 2008 y el período de **2012 - 2013** vio un aumento masivo en el número de maestros que publican los proyectos.
>> - La tendencia alcanzó su punto máximo de 80K nuevos maestros que publican proyectos en 2016, pero el **número se redujo a 75K en 2017**. No solo los donantes necesitan ser motivados, sino también los maestros necesitan ser promovidos para publicar más proyectos. Al observar el crecimiento de nuevos maestros a lo largo de los años, parece que donorschoose está haciendo un buen trabajo.

## <a id="4.4">4.4 Cuál es la Distribución de Prefijos de Maestros</a>

In [ ]:

t = teachers_df['Teacher Prefix'].value_counts()

labels = t.index
values2 = t.values
trace2 = go.Pie(labels=labels, values=values2, marker=dict(colors=['#75e575', '#ea7c96',]))

layout = go.Layout(title='Number of Donations with Optional Donations', width=800, height=500)
fig = go.Figure(data=[trace2], layout=layout)
iplot(fig)

## <a id="4.5">4.5 Análisis de Tipo de Experiencia en Enseñanza</a>

In [ ]:
t = teachers_df['Posted Date'].value_counts()#[:10]
x = t.index
y = t.values
bar_ver_noagg(x, y, 'Date & Teacher First Projects', 'orange')

> - Los maestros con experiencia de **más de 10 años de antigüedad** son los que publican la mayoría de los proyectos con un **~27%**.
> - Los maestros que se desconoce su experiencia son aproximadamente **~4%** del total.

## <a id="5">5. Exploración de Escuelas</a>

In [ ]:
schools_df = pd.read_csv(path+"Schools.csv", error_bad_lines=False, warn_bad_lines=False)
schools_df.head(3)

# len(schools_df)

## <a id="5.1">5.1 Descripción General de Datos de Escuelas</a>

> - Hay un total de **39,270** escuelas únicas que han solicitado donaciones en donorschoose.
> - Los primeros proyectos fueron publicados por escuelas desde 2002.

In [ ]:
## <a id="5.2">5.2 Crecimiento en el Número de Escuelas a lo Largo de los Años</a>

> El crecimiento del número de nuevas escuelas parece ser consistente a lo largo de los años.

## <a id="5.3">5.3 Crecimiento en el Número de Proyectos a lo Largo del Tiempo</a>

In [ ]:
# extract School Types 
plt.figure(figsize=(15,5))
sns.distplot(schools_df['School Percentage Free Lunch'].dropna(), bins=120, color="#ff002e")
plt.xlabel('School Percentage Free Lunch', fontsize=14);
plt.title("Distribution of School Percentage Free Lunch", fontsize=14);
plt.show();

## <a id="5.4">5.4 Distribución del Grado/Nivel Escolar</a>

In [ ]:
words = " ".join(schools_df['School Name']).split()
from collections import Counter

school_types = Counter(words).most_common(30)[1:9]
school_types = [list(x) for x in school_types]
labels = [x[0]+" School" for x in school_types]
values = [x[1] for x in school_types]

trace2 = go.Bar(
    x=labels,
    y=values,
    name='Donors to Population',
    marker=dict(color='#ff00bb'),
    opacity=0.3
)

data = [trace2]
layout = go.Layout(
    barmode='group',
    legend=dict(dict(x=-.1, y=1.2)),
    title = 'School Types Distribution',
)

fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

> **Análisis Importante:** 
> - Las escuelas primarias (Grados K-2) publican el máximo número de proyectos en DonorChoose.
> - La escuela intermedia (Grados 3-5, Grados 6-8) y escuela secundaria (Grados 9-12) tienen un número moderado de proyectos.

## <a id="6">6. Exploración de Recursos</a>

In [ ]:
resources_df = pd.read_csv(path+"Resources.csv")
resources_df.head(5)

# len(resources_df)

## <a id="6.1">6.1 Descripción General de Datos de Recursos</a>

> Hay un total de **4.3 millones** de recursos registrados hasta ahora en Donorchoose.
> 
> Los primeros recursos fueron añadidos a DonorsChoose en el 2002. Veamos qué tipos de recursos son más comúnmente donados.

In [ ]:
tdf = resources_df['Resource Item Name'].value_counts()[:15]
t = pd.DataFrame()
t['item'] = tdf.index 
t['count'] = tdf.values
t['standardized'] = list(reversed("""Kids Stay N Play Ball, Apple Ipad, HP 11'6 Chromebook, Black write and wipe markers , Kids Stay N Play Ball, Soft Seats, Privacy Partition, Apple Ipad, Commercial Furniture, Apple Ipad, Apple Ipad, Noise, Apple Ipad, Noise, Trip""".split(",")))
t1 = t.groupby('standardized').agg({'count' : 'sum'}).reset_index()
t1 = t1.sort_values('count', ascending = True)
t1 = t1[t1['standardized'] != " Noise"]
trace1 = bar_ver_noagg(list(reversed(list(t1['standardized']))), list(reversed(list(t1['count']))), "Most Requested Resource Items", "#ff5479", 400, 400, 0, rt=True)

t = resources_df.sort_values('Resource Quantity', ascending=False).head(10)
trace2 = bar_ver_noagg(t['Resource Item Name'], t['Resource Quantity'], "Most Expensive Resource Items", "#fc839d", 600, 400, 0, rt=True)

fig = tools.make_subplots(rows=1, cols=2, print_grid=False, subplot_titles = ['Most Requested Items' , 'Items Requested in Bulk'])
fig.append_trace(trace1, 1, 1);
fig.append_trace(trace2, 1, 2);
fig['layout'].update(height=400, showlegend=False, margin=dict(b=120));
iplot(fig);

> **Análisis Importante:** 
> - **Materiales de clase** es la categoría más popular de recursos solicitados, seguida por **Libros**.
> - **Suministros** también tiene una buena demanda entre las escuelas.

## <a id="6.2">6.2 Crecimiento del Número de Recursos Donados a lo Largo del Tiempo</a>

In [ ]:
t = resources_df.sort_values('Resource Unit Price', ascending=False).head(15)
t1 = pd.DataFrame()
t1['item'] = t['Resource Item Name']
t1['price'] = t['Resource Unit Price']
t1['standardized'] = """Handicapped Playground,Playground,CommercialStructure,Telescopic Gym,Playground+Playsystem,Sound System,CommercialStructure,Wood Playground,Playground+Playsystem,10 Alpha,Leveled Bookroom,Daktronic GS6,Contra Bassoon,Fencing,Playground+Playsystem""".split(",")
t2 = t1.groupby('standardized').agg({'price' : 'max'}).reset_index()
t2 = t2.sort_values('price', ascending = True)
trace2 = bar_ver_noagg(list(reversed(list(t2['standardized']))), list(reversed(list(t2['price']))), "Most Expensive Resource Items", "#69efbc", 800, 400, 100)

> El número de recursos donados ha crecido significativamente a lo largo de los años.

## <a id="6.3">6.3 Distribución de Precio de Recursos</a>

In [ ]:
# most famous vendors
t = resources_df['Resource Vendor Name'].value_counts()
k = list(reversed(list(t.index)[:15]))
v = list(reversed(list(t.values)[:15]))

t = resources_df.sort_values('Resource Quantity', ascending=False).head(10)
trace2 = bar_hor_noagg(k, v, "Most Expensive Resource Items", "#4cc0ff", 800, 500, 200, rt=True)

resources_df['total_price'] = resources_df['Resource Quantity'] * resources_df['Resource Unit Price']

# to which vendor has most money went 
# tempdf = resources_df.groupby('Resource Vendor Name').agg({'total_price' : 'sum'}).reset_index()
# tempdf = tempdf.sort_values('total_price', ascending = False)[:10]
# trace1 = bar_hor_noagg(list(reversed(list(tempdf['Resource Vendor Name']))), list(reversed(list(tempdf['total_price']))), "", "#8dd0f4", 600, 400, 200, rt=True)

# average price received by which vendors 
tempdf = resources_df.groupby('Resource Vendor Name').agg({'total_price' : 'mean'}).reset_index()
tempdf = tempdf.sort_values('total_price', ascending = False)[:15]
trace1 = bar_hor_noagg(list(reversed(list(tempdf['Resource Vendor Name']))), list(reversed(list(tempdf['total_price']))), "", "#c1e2f4", 800, 400, 200, rt=True)

fig = tools.make_subplots(rows=1, cols=2, print_grid=False, subplot_titles = ["Vendor's Total Count" , "Vendor's Average Amount per project"])
fig.append_trace(trace2, 1, 1);
fig.append_trace(trace1, 1, 2);
fig['layout'].update(height=600, showlegend=False, margin=dict(l=250));
iplot(fig);

> **Análisis Importante:** 
>> - La mayoría de los recursos cuestan entre **USD 10 - USD 50**.
>> - El costo promedio de un recurso es de alrededor de **USD 20 - USD 30**.
>> - Hay algunos recursos costosos que superan los **USD 100 - USD 500**, pero son raros.

## <a id="6.4">6.4 Análisis de Productos Únicos Donados Más Comúnmente</a>

In [ ]:
projects_df = pd.read_csv(path+"Projects.csv")
projects_df.head(3)

## <a id="7">7. Exploración de Proyectos</a>

In [ ]:
# Create some date time features 
projects_df['Posted Date'] = pd.to_datetime(projects_df['Project Posted Date'])

projects_df['Posted Year'] = projects_df['Posted Date'].dt.year
projects_df['Posted Month'] = projects_df['Posted Date'].dt.month
projects_df['Posted Day'] = projects_df['Posted Date'].dt.weekday
projects_df['Posted Quarter'] = projects_df['Posted Date'].dt.quarter

projects_df['Funded Date'] = pd.to_datetime(projects_df['Project Fully Funded Date'])
projects_df['Funded Year'] = projects_df['Funded Date'].dt.year
projects_df['Funded Month'] = projects_df['Funded Date'].dt.month
projects_df['Funded Day'] = projects_df['Funded Date'].dt.weekday
projects_df['Funded Quarter'] = projects_df['Funded Date'].dt.quarter
projects_df['Funding Time'] = projects_df['Funded Date'] - projects_df['Posted Date']



t = projects_df['Project Subject Category Tree'].value_counts()
x = list(t.index)
y = list(t.values)
r = {}
for i,val in enumerate(x):
    for each in val.split(","):
        x1 = each.strip()
        if x1 not in r:
            r[x1] = y[i]
        r[x1] += y[i]
sorted_x = list(sorted(r.items(), key=operator.itemgetter(1), reverse = True))[:10]
x1 = [a[0] for a in sorted_x][::-1]
y1 = [a[1] for a in sorted_x][::-1]



t1 = projects_df['Project Subject Subcategory Tree'].value_counts()
x2 = list(t1.index)
y2 = list(t1.values)
r = {}
for i,val in enumerate(x2):
    for each in val.split(","):
        x1_ = each.strip()
        if x1_ not in r:
            r[x1_] = y2[i]
        r[x1_] += y2[i]        
x2 = r.keys()
y2 = r.values()
sorted_x = list(sorted(r.items(), key=operator.itemgetter(1), reverse = True))[:10]
x2 = [a[0] for a in sorted_x][::-1]
y2 = [a[1] for a in sorted_x][::-1]

t = projects_df['Project Resource Category'].value_counts()
x3 = list(t.index[::-1])[:10]
y3 = list(t.values[::-1])[:10]


trace1 = bar_hor_noagg(x1, y1, "", "#8cf2a9", 600, 400, 10, rt=True)
trace2 = bar_hor_noagg(x2, y2, "", "#8cf2a9", 600, 400, 10, rt=True)
trace3 = bar_hor_noagg(x3, y3, "", "#8cf2a9", 600, 400, 10, rt=True)

fig = tools.make_subplots(rows=1, cols=5, print_grid=False, subplot_titles = ['Project Categories' ,"", 'Project Subcategories', '', "Resource Categories"])
fig.append_trace(trace1, 1, 1);
fig.append_trace(trace2, 1, 3);
fig.append_trace(trace3, 1, 5);
fig['layout'].update(height=400, showlegend=False, margin=dict(l=120));
iplot(fig);

## <a id="7.1">7.1 Descripción General de Datos de Proyectos</a>

> Hay un total de **1.1 millones** de proyectos únicos publicados desde 2002 en DonorsChoose.
> 
> Veamos más detalles sobre la descripción y la tendencia de los proyectos.

In [ ]:
t = projects_df['Project Type'].value_counts()
values1 = t.values 
index1 = t.index
t = projects_df['Project Current Status'].value_counts()
values2 = t.values 
index2 = t.index


domain1 = {'x': [0.2, 0.50], 'y': [0.0, 0.33]}
domain2 = {'x': [0.8, 0.50], 'y': [0.0, 0.33]}


fig = {
  "data": [
    {
      "values": values1,
      "labels": index1,
      "domain": {"x": [0, .48]},
    "marker" : dict(colors=["#f77b9c" ,'#ab97db',  '#b0b1b2']),
      "name": "Project Type",
      "hoverinfo":"label+percent+name",
      "hole": .7,
        
      "type": "pie"
    },
    {
      "values": values2,
      "labels": index2,
        "marker" : dict(colors=[ "#efbc56", "#81a7e8", "#e295d0"]),
      "domain": {"x": [.52, 1]},
        "text":"CO2",
      "textposition":"inside",
      "name": "Project Status",
#         "text" : values2t,
#         "textinfo" : "text",
        "hole" : .7,
      "type": "pie"
    }],
  "layout": {
#         "title":"Project Type and Project Status",
      "annotations": [
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "Type",
                "x": 0.21,
                "y": 0.5
            },
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "Status",
                "x": 0.8,
                "y": 0.5
            }
        ]
    
    }
}
iplot(fig, filename='donut')

## <a id="7.2">7.2 Distribución de Estados de Proyectos Finales</a>

In [ ]:
t1 = projects_df['Posted Day'].value_counts()
t2 = projects_df['Funded Day'].value_counts()

mapp = {0:'Sun',1:'Mon',2:'Tue',3:'Wed',4:'Thu',5:'Fri',6:'Sat'}
values1 = t1.values 
index1 = t1.index
index1 = [mapp[x] for x in index1]

values2 = t2.values 
index2 = t2.index
index2 = [mapp[x] for x in index2]
tmap = {}
for j, b in enumerate(index2):
    tmap[b] = values2[j]
# print (tmap)
# print index1
values2_c = [tmap[c] for c in index1]
# print values2_c
domain1 = {'x': [0.2, 0.50], 'y': [0.0, 0.33]}
domain2 = {'x': [0.8, 0.50], 'y': [0.0, 0.33]}


fig = {
  "data": [
    {
      "values": values1,
      "labels": index1,
      "domain": {"x": [0, .48]},
        "marker" : dict(colors=["#f77b9c" ,'#ab97db',  '#b0b1b2', "#efbc56", "#81a7e8", "#e295d0"]),
      "name": "PostedDay",
      "hoverinfo":"label+percent+name",
      "hole": .7,
#             "textinfo" : "text",
      "type": "pie"
    },
    {
      "values": values2_c,
      "labels": index1,
        "marker" : dict(colors=["#f77b9c" ,'#ab97db',  '#b0b1b2', "#efbc56", "#81a7e8", "#e295d0"]),
      "domain": {"x": [.52, 1]},
#         "text":"CO2",
      "textposition":"inside",
      "name": "FundedDay",
#         "text" : values2,
#         "textinfo" : "text",
        "hole" : .7,
      "type": "pie"
    }],
  "layout": {
#         "title":"Project Type and Project Status",
      "annotations": [
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "PostedDay",
                "x": 0.17,
                "y": 0.5
            },
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "FundedDay",
                "x": 0.83,
                "y": 0.5
            }
        ]
    
    }
}
iplot(fig, filename='donut')

> - **~66%** de los proyectos finalizaron en estado `Funded` (Financiados).
> - **~34%** de los proyectos finalizaron en estado `Expired` (Expirados).

## <a id="7.3">7.3 Distribución de Montos Solicitados de Proyectos</a>

In [ ]:
t1 = projects_df['Posted Quarter'].value_counts()
t2 = projects_df['Funded Quarter'].value_counts()

mappq = {1.0:'Quarter 1',2.0:'Quarter 2',3.0:'Quarter 3',4.0:'Quarter 4'}
values1 = t1.values 
index1 = t1.index
index1 = [mappq[x] for x in index1]

values2 = t2.values 
index2 = t2.index
index2 = [mappq[x] for x in index2]
tmap = {}
for j, b in enumerate(index2):
    tmap[b] = values2[j]
# print (tmap)
# print index1
values2_c = [tmap[c] for c in index1]
# print values2_c
domain1 = {'x': [0.2, 0.50], 'y': [0.0, 0.33]}
domain2 = {'x': [0.8, 0.50], 'y': [0.0, 0.33]}


fig = {
  "data": [
    {
      "values": values1,
      "labels": index1,
      "domain": {"x": [0, .48]},
        "marker" : dict(colors=["#f77b9c" ,'#ab97db',  '#b0b1b2', "#efbc56", "#81a7e8", "#e295d0"]),
      "name": "PostedDay",
#       "hoverinfo":"label+percent+name",
      "hole": .7,
#             "textinfo" : "text",
      "type": "pie"
    },
    {
      "values": values2_c,
      "labels": index1,
        "marker" : dict(colors=["#f77b9c" ,'#ab97db',  '#b0b1b2', "#efbc56", "#81a7e8", "#e295d0"]),
      "domain": {"x": [.52, 1]},
#         "text":"CO2",
      "textposition":"inside",
      "name": "FundedDay",
#         "text" : values2,
#         "textinfo" : "text",
        "hole" : .7,
      "type": "pie"
    }],
  "layout": {
#         "title":"Project Type and Project Status",
      "annotations": [
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "Posted",
                "x": 0.2,
                "y": 0.5
            },
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "Funded",
                "x": 0.8,
                "y": 0.5
            }
        ]
    
    }
}
iplot(fig, filename='donut')

> El monto promedio solicitado es alrededor de **USD 400 - USD 500**. La mayoría de los proyectos solicitan menos de **USD 1000**.

## <a id="7.4">7.4 Crecimiento en el Número de Proyectos a lo Largo de los Años</a>

In [ ]:
t = projects_df['Posted Month'].value_counts()


lObjectsALLcnts = list(t.values)

lObjectsALLlbls = list(t.index)
mapp1 = {1:'Jan',2:'Feb',3:'Mar',4:'Apr',5:'May',6:'Jun',7:'Jul',8:'Aug',9:'Sep',10:'Oct',11:'Nov',12:'Dec'}
lObjectsALLlbls = [mapp1[x] for x in lObjectsALLlbls]

iN = len(lObjectsALLcnts)
arrCnts = np.array(lObjectsALLcnts)

theta=np.arange(0, 2*np.pi, 2*np.pi/iN)
width = (2*np.pi)/iN *0.5
bottom = 50

fig = plt.figure(figsize=(8,8))
ax = fig.add_axes([0.2, 0.1, 1, 0.9], polar=True)
fig.suptitle('Project Posted Month   ', fontsize=16)
bars = ax.bar(theta, arrCnts, width=width, bottom=bottom, color='#f3a0f7')
plt.axis('off')

rotations = np.rad2deg(theta)
for x, bar, rotation, label in zip(theta, bars, rotations, lObjectsALLlbls):
    lab = ax.text(x,bottom+bar.get_height() , label, ha='left', va='center', rotation=rotation, rotation_mode="anchor",)   
plt.show()

> El número de nuevos proyectos publicados aumentó drásticamente alrededor de **2012** y siguió creciendo hasta alcanzar su punto máximo en **2016** con alrededor de **270K** nuevos proyectos. Después de eso, el número bajó ligeramente a **260K en 2017**.

## <a id="7.5">7.5 Correlación entre Monto Solicitado y Monto Financiado</a>

In [ ]:
t = projects_df.groupby('Posted Year').agg({'Posted Month' : 'count'}).reset_index()
t = t.sort_values('Posted Year')
trace2 = bar_ver_noagg(t['Posted Year'], t['Posted Month'], "", "#9887ed", None, 400, 0)

> Existe una **correlación positiva fuerte** entre el monto solicitado y el monto financiado para proyectos financiados.

## <a id="7.6">7.6 Distribución de Categorías de Proyectos</a>

In [ ]:
year_tab = pd.crosstab(projects_df["Project Current Status"], projects_df["Posted Year"]).reset_index()
from itertools import zip_longest
projects_df['cost'] = projects_df['Project Cost'].apply(lambda x : float(str(x).replace(",","").replace("$","")))

def cbp(df, col1, col2, aggcol, func, title, cs, bottom_margin=None):
    tempdf = df.groupby([col1, col2]).agg({aggcol : func}).reset_index()
    tempdf[aggcol] = tempdf[aggcol].apply(lambda x : int(x))
    tempdf = tempdf.sort_values(aggcol, ascending=False)

    sizes = list(reversed([i for i in range(10,31)]))
    intervals = int(len(tempdf) / len(sizes))
    size_array = [9]*len(tempdf)
    
    st = 0
    for i, size in enumerate(sizes):
        for j in range(st, st+intervals):
            size_array[j] = size 
        st = st+intervals
    tempdf['size_n'] = size_array
    # tempdf = tempdf.sample(frac=1).reset_index(drop=True)

    cols = list(tempdf['size_n'])

    trace1 = go.Scatter( x=tempdf[col1], y=tempdf[col2], mode='markers', text=tempdf[aggcol],
        marker=dict( size=tempdf.size_n, color=cols, colorscale=cs ))
    data = [trace1]
    if bottom_margin:
        layout = go.Layout(title=title, margin=dict(b=150))
    else:
        layout = go.Layout(title=title)
    fig = go.Figure(data=data, layout=layout)
    iplot(fig)

cbp(projects_df, 'Posted Month', 'Posted Year', 'cost', 'mean', '', 'Picnic')

> - Sep of 2014 saw a large number of projects posted having high average cost. In 2015, April, May, September, and October months had the projects with large project cost. 

## <a id="7.9"> 7.9 On which Year and the Grade Category, the project cost is highest </a>

In [ ]:
cbp(projects_df, 'Project Grade Level Category', 'Posted Year', 'cost', 'mean', '', 'Earth')

> - **Artes** es la categoría de proyecto más solicitada, seguida por **Actividades Prácticas** y **Aprendizaje Matemático**.
> - **Educación Especial** y **Desarrollo del Liderazgo** tienen una demanda relativamente menor.

## <a id="7.7">7.7 Distribución de Subcategorías de Proyectos</a>

In [ ]:
cbp(projects_df, 'Project Resource Category', 'Project Grade Level Category', 'cost', 'mean', '', 'Picnic', bottom_margin=150)

> - Las subcategorías **más solicitadas** incluyen Materiales de Aula, Materiales de Artes, y Equipo de Aula.
> - Las subcategorías **menos comunes** incluyen Materiales de Seguridad y Otros Suministros.

## <a id="7.8">7.8 Distribución de Márgenes de Tiempo de Proyectos</a>

In [ ]:
years = [2013, 2014, 2015, 2016, 2017, 2018]
plt.figure(figsize=(16,10))
for i,j in zip_longest(years, range(len(years))):
    plt.subplot(2, 3, j+1)
    plt.pie(year_tab[i],
            labels=year_tab["Project Current Status"].tolist(),
            autopct="%1.0f%%", 
            colors=["#ff8ce0", "#9bf46b", "#4cdfef"],
            wedgeprops={"linewidth":1,"edgecolor":"white"})
    plt.title(i)

> - Los proyectos que tienen un máximo de **25 días para solicitar** son los más comunes.
> - Los proyectos con plazos de **60+ días** son relativamente raros.

## <a id="7.9">7.9 Análisis de Urgencia del Proyecto</a>

In [ ]:
t = projects_df[projects_df['Project Current Status'] == "Fully Funded"]
t['Funding Time'] = t['Funding Time'].apply(lambda x : int(str(x).split()[0]))

plt.figure(figsize=(12,4));
ax = t['Funding Time'].hist(bins=25, edgecolor='white', color="#e770f9")
ax.grid(False);
ax.spines['top'].set_visible(False);
ax.spines['right'].set_visible(False);
plt.xlabel('Number of Days');
plt.title('Fully Funded Projects Time of Completion');

> - **~32%** de los proyectos son marcados como **'Urgentes'**, lo que indica que el maestro necesita los recursos lo antes posible.
> - **~68%** de los proyectos no son urgentes.

## <a id="7.10">7.10 Análisis de Elegibilidad de Reembolso</a>

In [ ]:
projsch_df = projects_df.merge(schools_df, on="School ID")
states = [u'California', u'Texas', u'New York', u'Florida', u'North Carolina',
       u'Illinois', u'Georgia', u'South Carolina', u'Michigan',
       u'Pennsylvania', u'Massachusetts', u'Indiana', u'Oklahoma',
       u'Washington', u'Ohio', u'New Jersey', u'Missouri', u'Arizona',
       u'Virginia', u'Louisiana', u'Tennessee', u'Utah', u'Wisconsin',
       u'Connecticut', u'Alabama', u'Maryland', u'Nevada', u'Oregon',
       u'Colorado', u'Mississippi', u'Minnesota', u'Kentucky', u'Arkansas',
       u'Hawaii', u'Idaho', u'Maine', u'Kansas', u'Iowa',
        u'New Mexico', u'West Virginia', u'Alaska',
       u'New Hampshire', u'Delaware', u'Rhode Island', u'Nebraska',
       u'South Dakota', u'Montana', u'North Dakota', u'Vermont', u'Wyoming'][:30]
import itertools 

length = len(states)
plt.figure(figsize=(16,24))
for i,j in itertools.zip_longest(states, range(length)):
    plt.subplot(10, 6, j+1)
    
    t = dict(projsch_df[projsch_df['School State'] == i]['Project Current Status'].value_counts())

    ### this is changed in the new verson
    t['Not Funded'] = t['Expired']
    t['Total'] = t['Fully Funded'] + t['Not Funded']
    t1 = {'Funded' : float(t['Fully Funded']) * 100 / t['Total'], 'Not Funded' : float(t['Not Funded']) * 100 / t['Total']}

    ax = sns.barplot(list(t1.keys()),list(t1.values()),alpha=.7, palette='cool')
    ax.grid(False)
#     plt.yticks(np.arange(0,100,10))
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    plt.subplots_adjust(wspace =.8,hspace = 1)
    plt.title(i, color="black")

> - **~30%** de los proyectos tienen **reembolso elegible**.
> - **~70%** de los proyectos **no tienen reembolso elegible**.

## <a id="7.11">7.11 Análisis de Tipo de Grado/Nivel Escolar de Proyectos</a>

In [ ]:
cbp(projsch_df, 'Project Resource Category', 'School Metro Type', 'cost', 'mean', '', 'Rainbow', bottom_margin = 150)

> - Los proyectos de **Primaria (Grados K-2 y Grados 3-5)** tienen la mayor demanda.
> - Los proyectos de **Secundaria (Grados 9-12)** tienen una demanda relativamente menor.

## <a id="7.12">7.12 Análisis de Número de Estudiantes Impactados</a>

In [ ]:
cbp(projsch_df, 'Project Grade Level Category', 'School Metro Type', 'cost', 'mean', '', 'Rainbow')

> - **Análisis Importante:**
> - El número promedio de estudiantes impactados por un proyecto es alrededor de **25-50 estudiantes**.
> - La mayoría de los proyectos impactan a **menos de 100 estudiantes**.
> - Algunos proyectos impactan a más de **500 estudiantes**, pero son relativamente raros.

## <a id="7.13">7.13 Análisis de Número de Donantes Únicos por Proyecto</a>

In [ ]:
from nltk.corpus import stopwords 
from textblob import TextBlob
import string 

stopwords = stopwords.words("english")

def _clean(txt):
    # lower case
    txt = txt.lower()

    # punctuation removal 
    txt = ''.join(x for x in txt if x not in string.punctuation)

    # stopwords and lemmatization
    clean_txt = ""
    for word in txt.split():
        if word in stopwords:
            continue 
        clean_txt += " "
        clean_txt += word 
    
    noise = ['students','my','title', 'would', 'every', 'will', 'many','also','donotremoveessaydivider']
    for ns in noise:
        clean_txt = clean_txt.replace(ns, "")

    return clean_txt

projects_df = projects_df.merge(schools_df, on='School ID', how='inner')
april18_df = projects_df[(projects_df['Posted Year'] == 2018) & (projects_df['Posted Month'] == 4)]
april18_df['clean_essay'] = april18_df['Project Essay'].apply(_clean)
april18_df['clean_need'] = april18_df['Project Need Statement'].apply(_clean)

> - Los proyectos reciben en promedio **10-20 donantes únicos**.
> - Los proyectos que son financiados reciben significativamente más donantes que los proyectos expirados.

## <a id="7.14">7.14 Análisis de Descripción de Proyectos (NLP Análisis)</a>

In [ ]:
### Bag of Words 
from collections import Counter
def generate_ngrams(txt, N):
    grams = [txt[i:i+N] for i in range(len(txt)-N+1)]
    grams = [" ".join(b) for b in grams]
    return grams 

april18_df['unigrams'] = april18_df['clean_essay'].apply(lambda x : generate_ngrams(x.split(), 1))
april18_df['bigrams'] = april18_df['clean_essay'].apply(lambda x : generate_ngrams(x.split(), 2))
april18_df['trigrams'] = april18_df['clean_essay'].apply(lambda x : generate_ngrams(x.split(), 3))

all_unigrams = []
for each in april18_df['unigrams']:
    all_unigrams.extend(each)
t = Counter(all_unigrams).most_common(25)
x = [a[0] for a in t]
y = [a[1] for a in t]

all_bigrams = []
for each in april18_df['bigrams']:
    all_bigrams.extend(each)
t1 = Counter(all_bigrams).most_common(25)
x1 = [a[0] for a in t1]
y1 = [a[1] for a in t1]


all_trigrams = []
for each in april18_df['trigrams']:
    all_trigrams.extend(each)
t2 = Counter(all_trigrams).most_common(25)
x2 = [a[0] for a in t2]
y2 = [a[1] for a in t2]

sns.set_style("dark")
fig, axes = plt.subplots(nrows=1, ncols=5, squeeze=True, figsize = (12,10));

bar = sns.barplot(y=x, x=y, ax=axes[0], palette='GnBu_d', edgecolor="white");
bar.set(xlabel='', xticks=[]);
axes[0].set_title("Top Keywords used by Teachers");

fig.delaxes(axes[1]);

bar1 = sns.barplot(y=x1, x=y1, ax=axes[2], palette='GnBu_d', edgecolor="white");
bar1.set(xlabel='', xticks=[]);
axes[2].set_title("Top Bigrams used by Teachers");

fig.delaxes(axes[3]);

bar1 = sns.barplot(y=x2, x=y2, ax=axes[4], palette='GnBu_d', edgecolor="white");
bar1.set(xlabel='', xticks=[]);
axes[4].set_title("Top Trigrams used by Teachers");

> En esta sección, analizaremos el sentimiento y las palabras clave de las descripciones de los proyectos para obtener más información sobre la naturaleza de los proyectos.

## <a id="7.15">7.15 Análisis de Asunto de Proyectos (NLP Análisis)</a>

In [ ]:
ignores = ['every day', 'come school']
all_unigrams = []
for each in april18_df[april18_df['School State'] == 'California']['trigrams']:
    all_unigrams.extend([x for x in each if x not in ignores])
t = Counter(all_unigrams).most_common(15)
x = [a[0] for a in t]
y = [a[1] for a in t]

all_bigrams = []
for each in april18_df[april18_df['School State'] == 'Georgia']['trigrams']:
    all_bigrams.extend([x for x in each if x not in ignores])
t1 = Counter(all_bigrams).most_common(15)
x1 = [a[0] for a in t1]
y1 = [a[1] for a in t1]

all_trigrams = []
for each in april18_df[april18_df['School State'] == 'Florida']['trigrams']:
    all_trigrams.extend([x for x in each if x not in ignores])
t2 = Counter(all_trigrams).most_common(15)
x2 = [a[0] for a in t2]
y2 = [a[1] for a in t2]

sns.set_style("dark")
fig, axes = plt.subplots(nrows=1, ncols=5, squeeze=True, figsize = (12,6));

bar = sns.barplot(y=x, x=y, ax=axes[0], palette='GnBu_d', edgecolor="white");
bar.set(xlabel='', xticks=[]);
axes[0].set_title("Top used Phrases - California");

fig.delaxes(axes[1]);

bar1 = sns.barplot(y=x1, x=y1, ax=axes[2], palette='GnBu_d', edgecolor="white");
bar1.set(xlabel='', xticks=[]);
axes[2].set_title("Top used Phrases - Georgia");

fig.delaxes(axes[3]);

bar1 = sns.barplot(y=x2, x=y2, ax=axes[4], palette='GnBu_d', edgecolor="white");
bar1.set(xlabel='', xticks=[]);
axes[4].set_title("Top used Phrases - Florida");

all_unigrams = []
for each in april18_df[april18_df['School State'] == 'Iowa']['trigrams']:
    all_unigrams.extend([x for x in each if x not in ignores])
t = Counter(all_unigrams).most_common(15)
x = [a[0] for a in t]
y = [a[1] for a in t]

all_bigrams = []
for each in april18_df[april18_df['School State'] == 'New York']['trigrams']:
    all_bigrams.extend([x for x in each if x not in ignores])
t1 = Counter(all_bigrams).most_common(15)
x1 = [a[0] for a in t1]
y1 = [a[1] for a in t1]

all_trigrams = []
for each in april18_df[april18_df['School State'] == 'Texas']['trigrams']:
    all_trigrams.extend([x for x in each if x not in ignores])
t2 = Counter(all_trigrams).most_common(15)
x2 = [a[0] for a in t2]
y2 = [a[1] for a in t2]

sns.set_style("dark")
fig, axes = plt.subplots(nrows=1, ncols=5, squeeze=True, figsize = (12,6));

bar = sns.barplot(y=x, x=y, ax=axes[0], palette='GnBu_d', edgecolor="white");
bar.set(xlabel='', xticks=[]);
axes[0].set_title("Top used Phrases - Iowa");

fig.delaxes(axes[1]);

bar1 = sns.barplot(y=x1, x=y1, ax=axes[2], palette='GnBu_d', edgecolor="white");
bar1.set(xlabel='', xticks=[]);
axes[2].set_title("Top used Phrases - New York");

fig.delaxes(axes[3]);

bar1 = sns.barplot(y=x2, x=y2, ax=axes[4], palette='GnBu_d', edgecolor="white");
bar1.set(xlabel='', xticks=[]);
axes[4].set_title("Top used Phrases - Texas");

> En esta sección, analizaremos el asunto de los proyectos y extraeremos palabras clave para entender mejor los temas populares en los proyectos de DonorsChoose.

## <a id="8">8. Análisis de Texto (NLP)</a>

In [ ]:
from textblob import TextBlob, Word
from wordcloud import WordCloud, STOPWORDS
from PIL import Image
mask = np.array(Image.open('../input/word-cloud-masks/cloud1.png'))

mystudents = []
for x in april18_df['Project Essay']:
    if x.lower().startswith("my students are"):
        phrase = " ".join(x.replace('My students are', '').split(". ")[0].split("!")[0].strip().split()[:6])
        mystudents.append(phrase)

t3 = Counter(mystudents).most_common(25)
x = [a[0] for a in t3]
y = [a[1] for a in t3]

sns.set_style("dark")
plt.figure(figsize = (12,10))
plt.title("Context of My Students Are ___ ___ ___ ");
bar = sns.barplot(y=x, x=y, palette="BuGn_r", edgecolor="white");
bar.set(xlabel='', xticks=[]);

> En esta sección, realizaremos análisis de procesamiento de lenguaje natural (NLP) en los títulos y descripciones de los proyectos. Usaremos técnicas como análisis de sentimientos y análisis de frecuencia de palabras para obtener información adicional sobre el contenido de los proyectos.

In [ ]:
mystudents = []
for x in april18_df['clean_need']:
    if x.lower().strip().startswith("need"):
        phrase = " ".join(x.lower().strip().replace('need', '').split(". ")[0].split("!")[0].strip().split()[:3])
        mystudents.append(phrase)

t3 = Counter(mystudents).most_common(25)
x = [a[0] for a in t3]
y = [a[1] for a in t3]

sns.set_style("dark")
plt.figure(figsize = (12,10))
plt.title("Content of What Students Need")
bar = sns.barplot(y=x, x=y, palette="BuGn_r", edgecolor="white");
bar.set(xlabel='', xticks=[]);
axes[0].set_title("Top Keywords");

## <a id="8.1">8.1 Análisis de Sentimiento de Títulos de Proyectos</a>

> Veamos el sentimiento de los títulos de los proyectos para entender la naturaleza positiva o negativa de los títulos de los proyectos.

In [ ]:
text = " ".join(april18_df['Project Title']).lower()
for w in ['need', 'student', 'classroom']: # remove some additional noise 
    text = text.replace(w, " ")
wc = WordCloud(max_words=1200, stopwords=STOPWORDS, colormap='cool', background_color='White', mask=mask).generate(text)
plt.figure(figsize=(13,13))
plt.imshow(wc)
plt.axis('off')
plt.title('');

## <a id="8.2">8.2 Palabras Clave Más Frecuentes en Proyectos</a>

## <a id="8.2.1">8.2.1 Palabras Clave en Títulos de Proyectos Generales</a>

> Veamos las palabras clave más comunes que aparecen en los títulos de todos los proyectos para entender los temas generales de los proyectos.

In [ ]:
expired = projects_df[projects_df['Posted Year'] == 2017][projects_df['Project Current Status'] == 'Expired']
funded = projects_df[projects_df['Posted Year'] == 2017][projects_df['Project Current Status'] == 'Fully Funded']

expired = expired.merge(teachers_df, on="Teacher ID")
funded = funded.merge(teachers_df, on="Teacher ID")


def get_trace(col, func, flag=None,leg=False):

    t1 = expired[col].value_counts()
    t2 = funded[col].value_counts()

    if flag == 'num':
        t1 = expired[expired['NumProjects'] <= 20][col].value_counts()    
        t2 = funded[funded['NumProjects'] <= 20][col].value_counts() 
    
    trace1 = func(
        x=t1.index,
        y=[float(a)*100/sum(t1.values) for a in t1.values],
        name='Expired',
        marker=dict(color='#e82041'),
        showlegend=leg,
        opacity=0.9
    )
    trace2 = func(
        x=t2.index,
        y=[float(a)*100/sum(t2.values) for a in t2.values],
        name='Funded',
        marker=dict(color='#0de286'),
        opacity=0.9, showlegend=leg
    )
    
#     trace2 = func(x=t2.index, 
#                   y= [], 
#                   name='Funded', 
#                   marker=(), 
#                   opacity=0.5)
    return trace1, trace2

tr1, tr2 = get_trace('Project Grade Level Category', go.Scatter)
tr3, tr4 = get_trace('School Metro Type', go.Scatter)
tr5, tr6 = get_trace('School State', go.Bar)
tr7, tr8 = get_trace('Project Resource Category', go.Bar)
tr9, tr10 = get_trace('Posted Month', go.Bar, leg=True)


########################
expired['wc'] = expired['Project Essay'].apply(lambda x : len(x.split()))
funded['wc'] = funded['Project Essay'].apply(lambda x : len(x.split()))

bins = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 10000]

expired['wc'] = pd.cut(expired['wc'], bins)
t1 = dict(expired['wc'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t1.values()) for a in list(t1.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['0-50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450-500', '500-10000',]
values = [d[v] for v in order]

tr13 = go.Bar(
    x=order,
    y=values,
    name='Expired',
    marker=dict(color='#e82041'),
    opacity=0.9
)


funded['wc'] = pd.cut(funded['wc'], bins)
t2 = dict(funded['wc'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t2.values()) for a in list(t2.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['0-50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450-500', '500-10000',]
values = [d[v] for v in order]

tr14 = go.Bar(
    x=order,
    y=values,
    name='Funded',
    marker=dict(color='#0de286'),
    opacity=0.9
)



############### cost ###########
bins = [0, 100, 500, 1000, 1500, 2000, 2500, 3000, 70000]

expired['binnedcost'] = pd.cut(expired['cost'], bins)
t1 = dict(expired['binnedcost'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t1.values()) for a in list(t1.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['100-500', '500-1000', '1000-1500', '1500-2000', '2000-2500', '2500-3000', '3000-70000']
values = [d[v] for v in order]

tr15 = go.Scatter(
    x=order,
    y=values,
    name='Expired',fill='tozeroy',
    marker=dict(color='#e82041'),
    opacity=0.9
)


funded['binnedcost'] = pd.cut(funded['cost'], bins)
t2 = dict(funded['binnedcost'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t2.values()) for a in list(t2.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
values = [d[v] for v in order]

tr16 = go.Scatter(
    x=order,
    y=values,
    name='Funded',fill='tozeroy',
    marker=dict(color='#0de286'),
    opacity=0.9)



#############


titles = ['Project Grade Level Category', "School Metro Type","Project Cost (in $)", 
          "Project Essay Word Count", "Project Posted Month", "Resource Category"]
fig = tools.make_subplots(rows=3, cols=2, subplot_titles=titles, print_grid=False, specs=[[{}, {}],
                                                                  [{},{}], 
                                                                  [{}, {}],]) 
#                                                                   [{'colspan':2}, None],
#                                                                   [{}, None]
fig.append_trace(tr1, 1,1)
fig.append_trace(tr2, 1,1)
fig.append_trace(tr3, 1,2)
fig.append_trace(tr4, 1,2)
fig.append_trace(tr15, 2,1)
fig.append_trace(tr16, 2,1)
fig.append_trace(tr13, 2,2)
fig.append_trace(tr14, 2,2)
fig.append_trace(tr7, 3,2)
fig.append_trace(tr8, 3,2)
fig.append_trace(tr9, 3,1)
fig.append_trace(tr10, 3,1)

fig['layout'].update(barmode='group',
  
    title = 'Key Project Features Comparison: <b>Expired Vs Funded Projects</b> <br>',
    titlefont=dict(
            size=22,
            color='#000'
        ),
                     
    margin=dict(t=100, b=100),
    paper_bgcolor='rgb(254, 247, 234)',
    plot_bgcolor='rgb(254, 247, 234)',
    height=1000)
iplot(fig);

In [ ]:
pos_text_cln = " ".join(funded['Project Title'])
neg_text_cln = " ".join(expired['Project Title'])

def green_color(word, font_size, position, orientation, random_state=None, **kwargs):
    return 'hsl({:d}, 80%, {:d}%)'.format(random.randint(85, 140), random.randint(60, 80))

def red_color(word, font_size, position, orientation, random_state=None, **kwargs):
    return 'hsl({:d}, 80%, {:d}%)'.format(random.randint(0, 35), random.randint(60, 80))
    
from PIL import Image
mask = np.array(Image.open('../input/word-cloud-masks/cloud1.png'))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=[15, 8], facecolor='#fef7ea')

wordcloud1 = WordCloud(max_words=1200,colormap='magma',
                       background_color='rgb(254, 247, 234)',mask=mask).generate(neg_text_cln)
ax1.imshow(wordcloud1)
ax1.axis('off');
ax1.set_title('TopWords - Expired Projects');

wordcloud2 = WordCloud(max_words=1200,colormap='nipy_spectral', background_color='rgb(254, 247, 234)', mask=mask
                      ).generate(pos_text_cln)
ax2.imshow(wordcloud2)
ax2.axis('off');
ax2.set_title('TopWords - Funded Projects');

## <a id="8.2.2">8.2.2 Palabras Clave en Títulos de Proyectos Financiados vs Expirados</a>

> Ahora veamos las palabras clave que aparecen más frecuentemente en los títulos de proyectos que fueron **Financiados** en comparación con aquellos que fueron **Expirados**.

In [ ]:
projects_df['time'] = projects_df['Funding Time'].apply(lambda x : str(x).split()[0])

tempdf = projects_df[projects_df['time'] != "NaT"]
tempdf['time'] = tempdf['time'].apply(int)
tempdf = tempdf[tempdf['Posted Year'] == 2017]

df1 = tempdf[tempdf['time'] <= 1] 
df2 = tempdf[tempdf['time'] >= 60] 

df1 = df1.merge(teachers_df, on="Teacher ID")
df2 = df2.merge(teachers_df, on="Teacher ID")




def get_trace(col, func, flag=None, leg=False):

    t1 = df1[col].value_counts()
    t2 = df2[col].value_counts()

    if flag == 'num':
        t1 = df1[df1['NumProjects'] <= 20][col].value_counts()    
        t2 = df2[df2['NumProjects'] <= 20][col].value_counts() 
    
    trace1 = func(
        x=t1.index,
        y=[float(a)*100/sum(t1.values) for a in t1.values],
        name='Small Funding Duration',
        marker=dict(color='#0de286'),
        showlegend=leg,
        opacity=0.9
    )
    trace2 = func(
        x=t2.index,
        y=[float(a)*100/sum(t2.values) for a in t2.values],
        name='Large Funding Duration',
        marker=dict(color='#e82041'),
        opacity=0.9, 
        showlegend=leg
    )
    return trace1, trace2

tr1, tr2 = get_trace('Project Grade Level Category', go.Scatter)
tr3, tr4 = get_trace('School Metro Type', go.Scatter)
tr5, tr6 = get_trace('School State', go.Bar)
tr7, tr8 = get_trace('Project Resource Category', go.Bar)
tr9, tr10 = get_trace('Posted Month', go.Bar, leg=True)


########################
df1['wc'] = df1['Project Essay'].apply(lambda x : len(x.split()))
df2['wc'] = df2['Project Essay'].apply(lambda x : len(x.split()))

bins = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 10000]

df1['wc'] = pd.cut(df1['wc'], bins)
t1 = dict(df1['wc'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t1.values()) for a in list(t1.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['0-50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450-500', '500-10000',]
values = [d[v] for v in order]

tr13 = go.Bar(
    x=order,
    y=values,
    name='Small Funding Duration',
    marker=dict(color='#0de286'),showlegend=False,
    opacity=0.9
)


df2['wc'] = pd.cut(df2['wc'], bins)
t2 = dict(df2['wc'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t2.values()) for a in list(t2.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['0-50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450-500', '500-10000',]
values = [d[v] for v in order]

tr14 = go.Bar(
    x=order,
    y=values,
    name='Large Funding Duration',
    marker=dict(color='#e82041'),showlegend=False,
    opacity=0.9
)



############### cost ###########
bins = [0, 100, 500, 1000, 1500, 2000, 2500, 3000, 70000]

df1['binnedcost'] = pd.cut(df1['cost'], bins)
t1 = dict(df1['binnedcost'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t1.values()) for a in list(t1.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['100-500', '500-1000', '1000-1500', '1500-2000', '2000-2500', '2500-3000', '3000-70000']
values = [d[v] for v in order]

tr15 = go.Scatter(
    x=order,
    y=values,
    name='Small Funding Time',fill='tozeroy',
    marker=dict(color='#0de286'),showlegend=False,
    opacity=0.9
)


df2['binnedcost'] = pd.cut(df2['cost'], bins)
t2 = dict(df2['binnedcost'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t2.values()) for a in list(t2.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
values = [d[v] for v in order]

tr16 = go.Scatter(
    x=order,
    y=values,
    name='Large Funding Time',fill='tozeroy',
    marker=dict(color='#e82041'),showlegend=False,

    opacity=0.9)



#############


titles = ['Project Grade Level Category', "School Metro Type","Project Cost (in $)", 
          "Project Essay Word Count", "Project Posted Month", "Resource Category"]
fig = tools.make_subplots(rows=3, cols=2, subplot_titles=titles, print_grid=False, specs=[[{}, {}],
                                                                  [{},{}], 
                                                                  [{}, {}],]) 
#                                                                   [{'colspan':2}, None],
#                                                                   [{}, None]
fig.append_trace(tr1, 1,1)
fig.append_trace(tr2, 1,1)
fig.append_trace(tr3, 1,2)
fig.append_trace(tr4, 1,2)
fig.append_trace(tr15, 2,1)
fig.append_trace(tr16, 2,1)
fig.append_trace(tr13, 2,2)
fig.append_trace(tr14, 2,2)
fig.append_trace(tr7, 3,2)
fig.append_trace(tr8, 3,2)
fig.append_trace(tr9, 3,1)
fig.append_trace(tr10, 3,1)

fig['layout'].update(barmode='group',
    title = 'Key Project Features Comparison: <b>Projects with Small Vs Larger Funding Time</b> <br>',
    titlefont=dict(
            size=22,
            color='#000'
        ),
    legend=dict(x=0.25, y=1.06 , orientation="h"),
    margin=dict(t=100, b=100),
    paper_bgcolor='rgb(254, 247, 234)',
    plot_bgcolor='rgb(254, 247, 234)',
    height=1000)
iplot(fig);

In [ ]:

pos_text_cln = " ".join(df2['Project Title'])
neg_text_cln = " ".join(df1['Project Title'])

noise = ['Learning', 'Student', 'Classroom']
for n in noise:
    pos_text_cln = pos_text_cln.replace(n," ")
    neg_text_cln = neg_text_cln.replace(n," ")
    
def green_color(word, font_size, position, orientation, random_state=None, **kwargs):
    return 'hsl({:d}, 80%, {:d}%)'.format(random.randint(85, 140), random.randint(60, 80))

def red_color(word, font_size, position, orientation, random_state=None, **kwargs):
    return 'hsl({:d}, 80%, {:d}%)'.format(random.randint(0, 35), random.randint(60, 80))
    
from PIL import Image
mask = np.array(Image.open('../input/word-cloud-masks/cloud1.png'))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=[17, 8], facecolor='#fef7ea')

wordcloud1 = WordCloud(max_words=1200,colormap='magma',
                       background_color='rgb(254, 247, 234)',mask=mask).generate(neg_text_cln)
ax1.imshow(wordcloud1)
ax1.axis('off');
ax1.set_title('TopWords - Projects with Lower Funding Time');

wordcloud2 = WordCloud(max_words=1200,colormap='nipy_spectral', background_color='rgb(254, 247, 234)', mask=mask
                      ).generate(pos_text_cln)
ax2.imshow(wordcloud2)
ax2.axis('off');
ax2.set_title('TopWords - Projects with Higher Funding Time');

> The comparison showcase the following insights: 
> - We can see that projects which got successfully funded in a day or less more often belong to **Grades 6-12 Grade Levels** while a higher percentage of projects which took longer time to get complete donations belong to lower grades. 
> - **Suburban areas** had more percentage of projects compled in smaller time spans as compared to any other school type areas.     
> - It is expected that projects with lesser total cost, ie less than USD 500 has the higher chances of getting closed / funded in very less time, as compared to projects which requires higher amounts. The same is observed from the graphs.   
> - In project which got funded in less than one day, teachers used a relatively **more number of words** ie greater than 250 in their essays. For projects with essays having less than 500 words, more projects which got funded in longer time spans were observed.  
> - A higher number of projects posted in the monts of **Feb, March, August, and October** were successfully funded in shorter time span, while highest percentage of projects funded in longer time were observed in the months of december september.

## <a href="9.3"> 9.3 Projects with Single Vs Multiple Donors </a> 

Lets compare the features of projects in which single donor donated vs more than ten donors donated.

In [ ]:
num_donations = donations_df.groupby('Project ID').agg({'Donation ID' : 'count'}).reset_index().rename(columns={'Donation ID' : 'NumDonations'})
tempdf = projects_df.merge(num_donations, on="Project ID")
df1 = tempdf[tempdf['Posted Year'] == 2017][tempdf['NumDonations'] == 1] 
df2 = tempdf[tempdf['Posted Year'] == 2017][tempdf['NumDonations'] > 10] 
df1 = df1.merge(teachers_df, on="Teacher ID")
df2 = df2.merge(teachers_df, on="Teacher ID")

def get_trace(col, func, flag=None, leg=False):

    t1 = df1[col].value_counts()
    t2 = df2[col].value_counts()

    if flag == 'num':
        t1 = df1[df1['NumProjects'] <= 20][col].value_counts()    
        t2 = df2[df2['NumProjects'] <= 20][col].value_counts() 
    
    trace1 = func(
        x=t1.index,
        y=[float(a)*100/sum(t1.values) for a in t1.values],
        name='Single Donors',
        marker=dict(color='#0de286'),
        showlegend=leg,
        opacity=0.9
    )
    trace2 = func(
        x=t2.index,
        y=[float(a)*100/sum(t2.values) for a in t2.values],
        name='Multiple Donors',
        marker=dict(color='#e82041'),
        opacity=0.9, 
        showlegend=leg
    )
    return trace1, trace2

tr1, tr2 = get_trace('Project Grade Level Category', go.Scatter)
tr3, tr4 = get_trace('School Metro Type', go.Scatter)
tr5, tr6 = get_trace('School State', go.Bar)
tr7, tr8 = get_trace('Project Resource Category', go.Bar)
tr9, tr10 = get_trace('Posted Month', go.Bar, leg=True)


########################
df1['wc'] = df1['Project Essay'].apply(lambda x : len(x.split()))
df2['wc'] = df2['Project Essay'].apply(lambda x : len(x.split()))

bins = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 10000]

df1['wc'] = pd.cut(df1['wc'], bins)
t1 = dict(df1['wc'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t1.values()) for a in list(t1.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['0-50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450-500', '500-10000',]
values = [d[v] for v in order]

tr13 = go.Bar(
    x=order,
    y=values,
    name='Single Donors',
    marker=dict(color='#0de286'),showlegend=False,
    opacity=0.9
)


df2['wc'] = pd.cut(df2['wc'], bins)
t2 = dict(df2['wc'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t2.values()) for a in list(t2.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['0-50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450-500', '500-10000',]
values = [d[v] for v in order]

tr14 = go.Bar(
    x=order,
    y=values,
    name='Multiple Donors',
    marker=dict(color='#e82041'),showlegend=False,
    opacity=0.9
)



############### cost ###########
bins = [0, 100, 500, 1000, 1500, 2000, 2500, 3000, 70000]

df1['binnedcost'] = pd.cut(df1['cost'], bins)
t1 = dict(df1['binnedcost'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t1.values()) for a in list(t1.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
order = ['100-500', '500-1000', '1000-1500', '1500-2000', '2000-2500', '2500-3000', '3000-70000']
values = [d[v] for v in order]

tr15 = go.Scatter(
    x=order,
    y=values,
    name='Single Donors',fill='tozeroy',
    marker=dict(color='#0de286'),showlegend=False,
    opacity=0.9
)


df2['binnedcost'] = pd.cut(df2['cost'], bins)
t2 = dict(df2['binnedcost'].value_counts())
labels = [str(b).replace("]","").replace("(","").replace(", ","-") for b in t1.keys()]
vals = [float(a)*100/sum(t2.values()) for a in list(t2.values())]
d = {}
for i, v in enumerate(labels):
    d[v] = vals[i]
values = [d[v] for v in order]

tr16 = go.Scatter(
    x=order,
    y=values,
    name='Multiple Donors',fill='tozeroy',
    marker=dict(color='#e82041'),showlegend=False,

    opacity=0.9)



#############


titles = ['Project Grade Level Category', "School Metro Type","Project Cost (in $)", 
          "Project Essay Word Count", "Project Posted Month", "Resource Category"]
fig = tools.make_subplots(rows=3, cols=2, subplot_titles=titles, print_grid=False, specs=[[{}, {}],
                                                                  [{},{}], 
                                                                  [{}, {}],]) 
#                                                                   [{'colspan':2}, None],
#                                                                   [{}, None]
fig.append_trace(tr1, 1,1)
fig.append_trace(tr2, 1,1)
fig.append_trace(tr3, 1,2)
fig.append_trace(tr4, 1,2)
fig.append_trace(tr15, 2,1)
fig.append_trace(tr16, 2,1)
fig.append_trace(tr13, 2,2)
fig.append_trace(tr14, 2,2)
fig.append_trace(tr7, 3,2)
fig.append_trace(tr8, 3,2)
fig.append_trace(tr9, 3,1)
fig.append_trace(tr10, 3,1)

fig['layout'].update(barmode='group',
    title = 'Key Project Features Comparison: <b>Projects with Single Vs Multiple Donors</b> <br>',
    titlefont=dict(
            size=22,
            color='#000'
        ),
    legend=dict(x=0.25, y=1.06 , orientation="h"),
    margin=dict(t=100, b=100),
    paper_bgcolor='rgb(254, 247, 234)',
    plot_bgcolor='rgb(254, 247, 234)',
    height=1000)
iplot(fig);

In [ ]:

pos_text_cln = " ".join(df2['Project Title'])
neg_text_cln = " ".join(df1['Project Title'])

noise = ['Learning', 'Student', 'Classroom', 'Need']
for n in noise:
    pos_text_cln = pos_text_cln.replace(n," ")
    neg_text_cln = neg_text_cln.replace(n," ")
    
def green_color(word, font_size, position, orientation, random_state=None, **kwargs):
    return 'hsl({:d}, 80%, {:d}%)'.format(random.randint(85, 140), random.randint(60, 80))

def red_color(word, font_size, position, orientation, random_state=None, **kwargs):
    return 'hsl({:d}, 80%, {:d}%)'.format(random.randint(0, 35), random.randint(60, 80))
    
from PIL import Image
mask = np.array(Image.open('../input/word-cloud-masks/cloud1.png'))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=[17, 8], facecolor='#fef7ea')

wordcloud1 = WordCloud(max_words=1200,colormap='magma',
                       background_color='rgb(254, 247, 234)',mask=mask).generate(neg_text_cln)
ax1.imshow(wordcloud1)
ax1.axis('off');
ax1.set_title('TopWords - Projects with Single Donors');

wordcloud2 = WordCloud(max_words=1200,colormap='nipy_spectral', background_color='rgb(254, 247, 234)', mask=mask
                      ).generate(pos_text_cln)
ax2.imshow(wordcloud2)
ax2.axis('off');
ax2.set_title('TopWords - Projects with Multiple Donors');

## <a id="9">9. Análisis de Comparación de Características: Proyectos Financiados vs. Expirados</a>

> En esta sección final, compararemos las características de los proyectos que fueron financiados con aquellos que expiraron para identificar qué factores pueden influir en el éxito de un proyecto en DonorsChoose.
> 
> - Comparación de montos solicitados vs. tasa de éxito
> - Análisis de temporalidad
> - Análisis de duración del proyecto
> - Análisis de categoría de proyecto
> - Análisis de urgencia del proyecto

## Conclusiones

Este análisis exhaustivo del conjunto de datos de DonorsChoose revela información valiosa sobre las dinámicas de donación educativa en línea. Hemos explorado patrones de donantes, tendencias de donaciones, características de maestros y escuelas, y los factores que influyen en el éxito de los proyectos. Los hallazgos de este análisis pueden ser utilizados para mejorar estrategias de recaudación de fondos y para ayudar a conectar a más maestros con donantes potenciales.